### ISSUE TITLE
Import of UXarray fails with a ValueError

### ISSUE THREAD

**Issue by airwarriorg91** [UXARRAY/uxarray#1008]
### Version

v2024.10.0

### How did you install UXarray?

Pip

### What happened?

Fails to import the library on calling `import uxarray as uxr`.

Error:
```
Traceback (most recent call last):
  File "C:\Users\gaura\OneDrive\Documents\test.py", line 7, in <module>
    import uxarray as uxr
  File "C:\Users\gaura\AppData\Roaming\Python\Python312\site-packages\uxarray\__init__.py", line 13, in <module>
    from .cmaps import sequential, diverging, sequential_blue, sequential_green
  File "C:\Users\gaura\AppData\Roaming\Python\Python312\site-packages\uxarray\cmaps.py", line 14, in <module>
    sequential = LinearSegmentedColormap.from_list(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gaura\AppData\Roaming\Python\Python312\site-packages\matplotlib\colors.py", line 1067, in from_list
    "red": np.column_stack([vals, r, r]),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gaura\AppData\Roaming\Python\Python312\site-packages\numpy\lib\shape_base.py", line 652, in column_stack
    return _nx.concatenate(arrays, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3
```

### What did you expect to happen?

Import the library. 

### Can you provide a MCVE to repoduce the bug?

```python
import uxarray as uxr
print('123')
```

**Comment by rajeeja** [comment]
Thanks for reporting this. We'll try to fix this ASAP. Meanwhile, try a lower python version

**Comment by philipc2** [comment]
Hi @airwarriorg91 

May you share a full print out all installed Python packages in your current environment?

**Comment by airwarriorg91** [comment]
Hi @philipc2,
Find the attached list of packages installed in my environment.
[installed_packages.txt](https://github.com/user-attachments/files/17350715/installed_packages.txt)

**Comment by philipc2** [comment]
> Hi @philipc2, Find the attached list of packages installed in my environment. [installed_packages.txt](https://github.com/user-attachments/files/17350715/installed_packages.txt)

Can you try updating `numpy` and `matplotlib` to their latest release and see if the issue persists?

**Comment by airwarriorg91** [comment]
I upgraded `numpy` and `matplotlib` which solved the issue ! Thanks !

**Comment by philipc2** [comment]
> I upgraded `numpy` and `matplotlib` which solved the issue ! Thanks !

Glad to help!
