### ISSUE TITLE
Cookbook "Foundations" Section

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#1057]
## General Revision Comments
- Revisions to the cookbook foundations section
- Most sections can remain mostly the same

## Notebooks
- Unstructured Grids
- Plotting Libraries
- Rendering Techniques

**Comment by erogluorhan** [comment]
See https://github.com/ProjectPythia/unstructured-grid-viz-cookbook/issues/16 and https://github.com/ProjectPythia/unstructured-grid-viz-cookbook/pull/24
