### ISSUE TITLE
Add Github About Section

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#110]
Our about section is currently empty. Adding a short high-level description similar to other packages would be good to have. Possible descriptions will be posted in the comments.

**Comment by philipc2** [comment]
**Adapted from Documentation**
> Xarray styled package for working with unstructured grid datasets following UGRID conventions

or

> Xarray styled package for reading and directly operating on unstructured grid datasets following standard conventions (UGRID, SCRIP, Exodus)

**Comment by anissa111** [comment]
@philipc2 How about a combination of the two?:

> Xarray styled package for reading and directly operating on unstructured grid datasets following UGRID conventions

**Comment by philipc2** [comment]
> @philipc2 How about a combination of the two?:
> 
> > Xarray styled package for reading and directly operating on unstructured grid datasets following UGRID conventions

I like how this sounds.

**Comment by anissa111** [comment]
Alright, don!
