### ISSUE TITLE
Robust implementation of `point_within_gca` using only Cartesian coordinates

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#1102]
### Proposed new feature or change:

# Robust implementation of `point_within_gca`using only Cartesian coordinates

The current implementation of `point_within_gca` is not robust enough because it relies on back-and-forth conversions between longitude/latitude and Cartesian coordinates to determine the result. This approach introduces potential inaccuracies and inefficiencies.

We need to rewrite `point_within_gca` to exclusively use Cartesian coordinates. This will improve both robustness and performance by eliminating unnecessary conversions.

## Acceptance Criteria
- The `point_within_gca` function should be rewritten to exclusively use Cartesian coordinates.
- Ensure that the implementation is robust and handles edge cases appropriately.
- Maintain or improve the performance compared to the current implementation.
- Add sufficient tests to validate the correctness of the rewritten function.

**Comment by philipc2** [comment]
Hi @hongyuchen1030 

Just wanted to clarify that `_point_within_gca_cartesian` isn't the primary function we should be calling. This one was implemented for compatibility and ease of use (i.e. for basic tests and examples,

We use the following primarily in our internal code, which expects both spherical and cartesian coordinates.

https://github.com/UXARRAY/uxarray/blob/1d20619dafe8b0f5aca1513ded0f3587c53756f7/uxarray/grid/arcs.py#L65-L275

I am all in favor of re-writing it to only use Cartesian coordinates though, especially if it will improve the accuracy.

**Comment by hongyuchen1030** [comment]
> point_within_gca

Got it. Will change the name accordingly. What I mean is to rewrite the functionality using pure cartesian

**Comment by philipc2** [comment]
Seems like the only helper called from `point_within_gca` that would need to be updated is `_decide_pole_latitude`, which currently expects the latitude in radians.

**Comment by hongyuchen1030** [comment]
> Seems like the only helper called from `point_within_gca` that would need to be updated is `_decide_pole_latitude`, which currently expects the latitude in radians.

The entire `point_within_gca` function algorithm must be rewritten heavily.  So we don't even know if we need `_decide_pole_latitude`
