### ISSUE TITLE
An Undirected `Edge` Class

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#111]
Currently, the `Edge` is undirected, which means these two edges: `[0, 1]` and `[1, 0]` should be considered equal.

#90 
Fixed this problem by introducing a custom `Edge` class:

`Edge` class is a helper Object for `build_edge_face_connectivity`. Since all edges are undirected, I need to use a custom `__hash__` and `__eq__ `function to define the equality of the two edges. This internal-use-only helper class was not intended to become a user API.

**Comment by erogluorhan** [comment]
Is there a future plan of extending the `Edge` class with other functions? If so, please discuss a bit about those functions.

Otherwise, if `Edge` is only designed for checking if two undirected edges are equal, a single utility function like the following would just work without an `Edge` class or hashing:

```
def _are_undirected_edges_equal(edge_1, edge_2):
    # edge_1 : list
    # edge_2 : list
    return set(edge_1) == set(edge_2)
```

**Comment by hongyuchen1030** [comment]
The reason I required the hash function is that I need to use `set` to store all edges so as to avoid any duplication. And after all my searching, creating the object with its own `__hash__` and `__eq__` functions is the better solution in python.

I have also considered checking if such an edge already existed in the list every time I packed it. But it will result in a `O(n^2)` time complexity.

**Comment by hongyuchen1030** [comment]
And I think this helper object is the same thing as any other helper function. If the idea of creating a Class for an object sounds very serious, we can always create a directory to store all these utilities to make the project architecture clean.

**Comment by erogluorhan** [comment]
> The reason I required the hash function is that I need to use `set` to store all edges so as to avoid any duplication. And after all my searching, creating the object with its own `__hash__` and `__eq__` functions is the better solution in python.
> 
> I have also considered checking if such an edge already existed in the list every time I packed it. But it will result in a `O(n^2)` time complexity.

If I am not mistaken, the code part in your another PR (codes around the Line 142 [here](https://github.com/UXARRAY/uxarray/pull/55/files#diff-93f6ca66ccba77109d776037f2925e663079c29d5c68233ec90ab1b58258cec0:~:text=mesh2_edge_nodes_set.add(Edge(%5Bface%5Bi%5D%2C%20face%5Bi%20%2B%201%5D%5D)))) is referred to here. If so, that is okay, but what I am saying is that Python has already built-in capabilities for that purpose (i.e. what the `Edge` class is currently doing). In such case, Python `set` of `frozenset` objects could already create a set of hashable objects, which would likely identically perform what `Edge._hash` and `Edge_eq` together are doing.  

We can discuss and figure out all these in an ad-hoc meeting if desired.

**Comment by erogluorhan** [comment]
> And I think this helper object is the same thing as any other helper function. If the idea of creating a Class for an object sounds very serious, we can always create a directory to store all these utilities to make the project architecture clean.

As long as the design choices are justified and consistently documented, everything is doable.

**Comment by hongyuchen1030** [comment]
> frozenset

Thank you so much for your information! I just tried representing the undirected edge using the `frozenset()`.  Yeah, I think the `edge` class can be replaced by the `frozenset()` object nicely! I will replace my following implementation with this later and update my current PR by removing the `Edge` class.
