### ISSUE TITLE
Should we allow user to specify when to write SCRIP output files in `grid.write`

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#114]
_Originally posted by @rljacob in https://github.com/UXARRAY/uxarray/issues/104#issuecomment-1234854790_

"I don't think there is enough reliable metadata in mapping files to tell if one is SCRIP.  We could make that the default:  if its not UGRID or exodus, must be SCRIP.   Else we need a way for the user to optionally specify."

This issue tries to explore if we should implement a way for the user to optionally specify.

**Comment by erogluorhan** [comment]
FYI: @rljacob

**Comment by rljacob** [comment]
Wouldn't the user always be specifying an output type when using grid.write  ?   I was thinking more about grid.read when I made my comment.

**Comment by erogluorhan** [comment]
> Wouldn't the user always be specifying an output type when using grid.write ? I was thinking more about grid.read when I made my comment.

Yes, but that is currently realized through the file extension user is providing to `write`. Maybe we should switch to taking in file type instead?

**Comment by rljacob** [comment]
What are the current rules for file extensions in uxarray?
