### ISSUE TITLE
Create a UXarray dev workflow (GitHub best practices) doc and share with the team

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#119]
As discussed in the team discussion meeting on Friday, Sep 2nd, put together a document, which can act like a preliminary Contributor's Guide, to describe:
- UXarray development flow
- GitHub practices

Any thoughts on this and/or requests that you'd like to see in such a doc @anissa111 @dcherian @hongyuchen1030 @michaelavs @paullric @rajeeja @rljacob ?

**Comment by rljacob** [comment]
to include: Commit message and PR description guidelines.  Branch naming conventions.
