### ISSUE TITLE
Add functionality to read/write ESMF files

### ISSUE THREAD

**Issue by michaelavs** [UXARRAY/uxarray#120]
**Describe the feature you'd like added to this project**
Uxarray currently does not support reading or writing ESMF files. ESMF files are another style of unstructured grids and would align well with the overall goals of Uxarray. This functionality is also described in the Uxarray roadmap. Should also help close #107 

**Link to original NCL functionality, if applicable**
NCL ESMF regridding functionality: https://www.ncl.ucar.edu/Applications/ESMF.shtml 

**Describe the solution you'd like**
Adding functionality to read ESMF to UGRID and then write from UGRID to ESMF

**Comment by philipc2** [comment]
@brianpm @erogluorhan 

Pinging this issue, I'll work on getting this supported!
