### ISSUE TITLE
UXarray's conda install not auto-installing some dependencies

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#121]
**Bug**
A clean conda environment setup with only installing UXarray is not auto-installing UXarray's dependencies such as `numba` and `netcdf4`, which leads to errors with importing uxarray.

**To Reproduce**
1. Run these commands in the order:
    `conda create --name try_uxarray python=3.9`
    `conda activate try_uxarray`
    `conda install uxarray`
3. Then, write a small script in which you have:
    `import uxarray as uxr`
5. It will give an error for the following line in `helpers.py`
    `from numba import njit, config`
7. Manually installing numba, i.e. `conda install numba`, will resolve this error, but after that, there will be another error with `xarray.open_dataset` because it needs `netcdf4`.
8. Manually installing netcdf4, i.e. `conda install netcdf4`, will resolve this error, then importing `uxarray` will be possible.

**Expected behavior**
`conda install uxarray` should have installed UXarray's dependencies `numba` and `netcdf4` (and maybe others?) automatically. 

That same behavior should be provided for PyPI installations as well.

**OS:**
MacOS Big Sure (v11.6.7)

**Comment by philipc2** [comment]
I was able to replicate the same issue on my Windows machine.

**Comment by erogluorhan** [comment]
This has been fixed; thanks @marodrig !
