### ISSUE TITLE
Better document how to open dataset opening

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#122]
The current  UXarray docs does not list the `dataset.open_dataset()` under user API even though it is the essential function to initialize Grid object by opening single or multiple datasets. This needs to be fixed.

Usage example(s) about using `open_dataset` would also be further helpful for the users.

_Originally posted by @brianpm in https://github.com/UXARRAY/uxarray/issues/107#issuecomment-1242076683_

**Comment by anissa111** [comment]
@philipc2 Oh, yup! Let me see what's going on there.
