### ISSUE TITLE
Passing through a list of paths for open_dataset

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#124]
The current implementation of `open_dataset()` supports opening a grid file and multiple data files by passing through the paths as arguments. However, even though this is convienent, there is still room for improving this functionality 

If we have a list of data paths called `data_paths`, currently we must do this to create a grid object:
`grid = ux.open_dataset(grid_path, data_paths[0], data_paths[1], data_paths[2])`

However, a more elegant approach would be to simply pass through a list of names.
`grid = ux.open_dataset(grid_path, data_paths)`

Any thoughts / suggestions?

**Comment by rajeeja** [comment]
Sure, that sounds like an easy and useful upgrade.
Is it often that there are many data files associated with a grid file? If so, how many typically?

**Comment by dcherian** [comment]
Does tuple unpacking work? `grid = ux.open_dataset(grid_path, *data_paths)`

**Comment by philipc2** [comment]
> Does tuple unpacking work? `grid = ux.open_dataset(grid_path, *data_paths)`

This does work! I'll make sure to comment on this in my usage notebook.
