### ISSUE TITLE
Use "UXarray" consistently in our docs

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#128]
Per the team decision on 9/2/2022, we'd like to use "UXarray", i.e. capitalized U and X, throughout our documentation to reflect "Unstructured Xarray". 

We need to apply this consistently to our docs and fix wherever it appeared in other formats such as uxarray (if not referring to a conda command etc.) or Uxarray, etc.

**Comment by philipc2** [comment]
Closed with the merge of #336
