### ISSUE TITLE
Data Access Usage Example 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#135]
Topics Covered
* Overview of UGRID conventions and it's relation to other conventions
* Examples with variables name with UGRID conventions and one in another convention
* `Grid.ds` direct accessing using original variable names
* `Grid.ds` accessing using `Grid.var_dict` 
* `Grid.Mesh2_node_x `(etc.) attribute accessing using UGRID conventions

**Comment by philipc2** [comment]
@erogluorhan I'll be working on this throughout the week, is there anything else you'd like me to cover in this notebook?

**Comment by erogluorhan** [comment]
> @erogluorhan I'll be working on this throughout the week, is there anything else you'd like me to cover in this notebook?

This outline looks great! I think you will discuss in the beginning how flexible UGRID is with variable namings, so you can relate our "standardized" variable access for different names.

**Comment by philipc2** [comment]
#164
