### ISSUE TITLE
Unify the coordinates conversion function

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#155]
There're currently two coordinates transformation helper functions. One is implemented by @rajeeja  and one is implemented by @hongyuchen1030. After discussions, we agree on using @hongyuchen1030's version.

**Comment by rajeeja** [comment]
Thanks, I will try this and get back to you as soon as possible

**Comment by hongyuchen1030** [comment]
> Thanks, I will try your branch and get back to you as soon as possible

Hi, I have created a new branch along with a PR for this issues. However, after I try modifying your `calculate_face_area` with my `_convert_node_lonlat_rad_to_xyz`, the testcases for the grid, and integrate fail.  (but all `test_helpers` instance passes) 

I wonder if you can take a look at it in the PR? Thank you very much!
