### ISSUE TITLE
Detecting & Splitting Faces that cross the Antemeridian 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#171]
## Overview 

The connectivity used to described unstructured grids typically assumes that the grid resides on a sphere. When you connect two nodes together to form an edge across the antimeridian, attempting to project them onto a 2D projection (as is the case with many visualizations) leads to an incorrect representation, where the edge spans across the projection when it should instead directly "wrap" to the other node.

**Comment by philipc2** [comment]
@rajeeja @paullric @erogluorhan 

I've been thinking of an ideal way to implement this since I started visualization unstructured grids this summer, however many of the approaches I've tried don't always guarantee that every cyclic face would be found. 

What's the best approach to catch these transitions from one half of the grid to the other half? I was considering implementing some DFA that would use x values as transitions into other states and depending on the results end up in some accepting or rejection state. 

Is there a way that we could utilize the fact that all face_node (x,y) pairs must be oriented in a counter-clockwise direction? Or maybe the face_area calculations?

**Comment by hongyuchen1030** [comment]
Hi, @philipc2 @ifranda as mentioned in the meeting, here's the sudo codes that you can refer to so as to find the anti-meridian face

* Helper Function sudo codes to detect if an edge is across the anti-meridian (longitude 0 in this case)
This function summarizes each anti-meridian scenario that you can refer to (If you want to do a more detailed operation on the antimeridian case) 

```python
def edge_antimeridian_case(gcr_cart)
        GCR0_lonlat = node_xyz_to_lonlat_rad(gcr_cart[0])
        GCR1_lonlat = node_xyz_to_lonlat_rad(gcr_cart[1])
        # If x0 ---> x1 is larger than 180 degrees (pi radians), then it will be the anti-meridian case
        # That requires redirection of the GCR: changes tp x1 ----> x0
        if abs(GCR1_lonlat[0] - GCR0_lonlat[0]) >= np.pi:
            pass

            # The x0--> 180 -->x1 case is larger than the 180degrees (pi radians) case
            # Need to redirect such that x0 --> 0 --> x1
            if GCR0_lonlat[0] <= np.pi <= GCR1_lonlat[0]:
                pass
            # The 180 --> x0-->360/0 --> x1 --> 180 case is larger than the 180degrees (pi radians) case
            # Need to redirect such that 180 --> x0 --> 0 --> x1 --> 180
            elif 2 * np.pi >= GCR1_lonlat[0] >= np.pi >= GCR1_lonlat[0] >= 0:
                pass

        # The anti-meridian case where 180 -->x0 --> 0 lon --> x1 --> 180 that doesn't require redirection.
        elif 2*np.pi > GCR0_lonlat[0] > np.pi > GCR1_lonlat[0] > 0:
            pass

```python

If all you want to do is to find out if this edge is anti-meridian or not, use the following branching:

```python
if abs(GCR1_lonlat[0] - GCR0_lonlat[0]) >= np.pi or 2*np.pi > GCR0_lonlat[0] > np.pi > GCR1_lonlat[0] > 0:
```

* The final function sudo codes that can help you detect if the face goes across the antimeridian

for each face, loop over each edge and use the above function to test if this edge is anti-meridian, if any of the edges is `True`(across the meridian), then the entire face is antimeridian.

Please let me know if you have any question about this

**Comment by philipc2** [comment]
> e, lo

Thank you so much for this! This is extremely helpful!

**Comment by hongyuchen1030** [comment]
Hi @philipc2 
 some update related to the issue I just posted #392 , we need to add the exception for edge larger or equal to 180 degree here.
 
 ```python
def edge_antimeridian_case(gcr_cart)

        # Special case: when the gcr and the point are all on the same longitude line:
        if gcr_lonlat_rad[0][0] == gcr_lonlat_rad[1][0] == 0:
            pass


        GCR0_lonlat = node_xyz_to_lonlat_rad(gcr_cart[0])
        GCR1_lonlat = node_xyz_to_lonlat_rad(gcr_cart[1])

        # The anti-meridian case Sufficient condition: absolute difference between the longitudes of the two
        # vertices is greater than 180 degrees (π radians): abs(GCRv1_lon - GCRv0_lon) > π
        if abs(GCRv1_lonlat[0] - GCRv0_lonlat[0]) >= np.pi:

            # The necessary condition: the pt longitude is on the opposite side of the anti-meridian
            # Case 1: where 0 --> x0--> 180 -->x1 -->0 case is not less than the 180degrees (pi radians)
            # 
            if GCRv0_lonlat[0] <= np.pi <= GCRv1_lonlat[0]:
                raise ValueError("All edge span should be less than 180 degree")
            
            # The necessary condition: the pt longitude is on the opposite side of the anti-meridian
            # Case 2: The anti-meridian case where 180 -->x0 --> 0 lon --> x1 --> 180 
            elif 2*np.pi > GCRv0_lonlat[0] > np.pi > GCRv1_lonlat[0] > 0:
                pass

```

If all you want to do is to find out if this edge is anti-meridian or not, use the following branching:

```python

**Comment by philipc2** [comment]
@hongyuchen1030 

Thank you for this! I've been using the [antimeridian](https://github.com/gadomski/antimeridian) package for my visualization work, and possibly for future analysis work if it's applicable. 

Here's a great [example](https://antimeridian.readthedocs.io/en/stable/the-algorithm.html) from their documentation outlining the algorithm, which appears to be similar to what was outlined here.

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030
> 
> Thank you for this! I've been using the [antimeridian](https://github.com/gadomski/antimeridian) package for my visualization work, and possibly for future analysis work if it's applicable.
> 
> Here's a great [example](https://antimeridian.readthedocs.io/en/stable/the-algorithm.html) from their documentation outlining the algorithm, which appears to be similar to what was outlined here.

I took a look at their algorithm. Yes, they basically employ the same steps we're doing here. I think it should be compatible with our future implementation
