### ISSUE TITLE
Cannot open an MPAS file with uxarray

### ISSUE THREAD

**Issue by ahijevyc** [UXARRAY/uxarray#175]
**Describe the bug**

uxarray does not recognize MPAS mesh. It gives a RuntimeError when creating the Grid object.

Alternative grid file path:
/glade/scratch/ahijevyc/nystrom/CNTL/2005082500/x1.2621442.grid.nc

**To Reproduce**
Steps to reproduce the behavior with geocat datafile:
```
import geocat.datafiles as gdf
import xarray as xr
# Base data path
base_path = "netcdf_files/MPAS/FalkoJudt/dyamond_1/30km/"

# Path to Grid file
grid_path = base_path + "x1.655362.grid_subset.nc"

# Paths to Data Variable files
var_names = ['diag.2016-08-20_00.00.00_subset.nc']
data_paths = [base_path + name for name in var_names]
# Open the Grid file
grid_ds = xr.open_dataset(gdf.get(grid_path))
import uxarray as ux
# Construct a UXarray Grid object from `grid_ds`
grid = ux.Grid(grid_ds)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [20], line 2
      1 # Construct a UXarray Grid object from `grid_ds`
----> 2 grid = ux.Grid(grid_ds)

File ~/miniconda3/envs/geocat-tutorials/lib/python3.10/site-packages/uxarray/grid.py:80, in Grid.__init__(self, dataset, **kwargs)
     77 # check if initializing from string
     78 # TODO: re-add gridspec initialization when implemented
     79 elif isinstance(dataset, xr.Dataset):
---> 80     self.mesh_type = parse_grid_type(dataset)
     81     self.__from_ds__(dataset=dataset)
     82 else:

File ~/miniconda3/envs/geocat-tutorials/lib/python3.10/site-packages/uxarray/helpers.py:45, in parse_grid_type(dataset)
     43     mesh_type = "ugrid"
     44 else:
---> 45     raise RuntimeError(f"Could not recognize dataset format.")
     46 return mesh_type
     48 # check mesh topology and dimension

RuntimeError: Could not recognize dataset format.
```
**Expected behavior**
Create Grid object without error.

**OS:**
NCAR JupyterHub lab

**Environment**
# packages in environment at /glade/u/home/ahijevyc/miniconda3/envs/geocat-tutorials:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h5764c6d_3    conda-forge
asttokens                 2.1.0              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
babel                     2.11.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
bottleneck                1.3.5           py310hde88566_1    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cartopy                   0.21.0          py310hcda3f9e_2    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cf_xarray                 0.7.4              pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_2    conda-forge
cftime                    1.6.2           py310hde88566_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
cmaps                     1.0.5              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.6           py310hbf28c38_0    conda-forge
cryptography              38.0.3          py310h597c629_0    conda-forge
curl                      7.86.0               h7bff187_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0          py310h5764c6d_1    conda-forge
dask                      2022.10.2          pyhd8ed1ab_0    conda-forge
dask-core                 2022.10.2          pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.3           py310hd8f1fbe_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.10.2          pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
eofs                      1.4.0                      py_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_hf0379b8_105    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hc2a2eb6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0          py310h5764c6d_1    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
fsspec                    2022.10.0          pyhd8ed1ab_0    conda-forge
geocat-comp               2022.10.1          pyha770c72_0    conda-forge
geocat-datafiles          2022.03.0          pyha770c72_0    conda-forge
geocat-f2py               2022.04.0       py310h8adf1f6_1    conda-forge
geocat-viz                2022.07.0          pyhd8ed1ab_0    conda-forge
geos                      3.11.0               h27087fc_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.74.1               h6239696_1    conda-forge
glib-tools                2.74.1               h6239696_1    conda-forge
gst-plugins-base          1.21.1               h3e40eee_1    conda-forge
gstreamer                 1.21.1               hd4edc92_1    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
importlib_resources       5.10.0             pyhd8ed1ab_0    conda-forge
ipykernel                 6.17.0             pyh210e3f2_0    conda-forge
ipython                   8.6.0              pyh41d4057_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jack                      1.9.21               he978b8e_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.17.0             pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.11.2          py310hff52083_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py310hff52083_1005    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1              pyhd8ed1ab_2    conda-forge
jupyter_server            1.23.0             pyhd8ed1ab_0    conda-forge
jupyterlab                3.5.0              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.16.2             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py310hbf28c38_1    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcap                    2.66                 ha37c62d_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  15.0.4          default_h2e3cab8_0    conda-forge
libclang13                15.0.4          default_h3a83d3e_0    conda-forge
libcups                   2.3.3                h3e49a29_2    conda-forge
libcurl                   7.86.0               h7bff187_1    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.2                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libllvm15                 15.0.4               h63197d8_0    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_106    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libpq                     14.5                 hd77ab85_1    conda-forge
libsndfile                1.1.0                h27087fc_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libudev1                  252                  h166bdaf_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libxslt                   1.1.37               h873f0b0_0    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvmlite                  0.39.1          py310h58363a5_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.1           py310ha00c094_1    conda-forge
lz4                       4.0.2           py310h5d5e884_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.1           py310h5764c6d_2    conda-forge
matplotlib                3.6.2           py310hff52083_0    conda-forge
matplotlib-base           3.6.2           py310h8d5ebf3_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
metpy                     1.3.1              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mpg123                    1.30.2               h27087fc_1    conda-forge
msgpack-python            1.0.4           py310hbf28c38_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.31               haf5c9bc_0    conda-forge
mysql-libs                8.0.31               h28c427c_0    conda-forge
nbclassic                 0.4.8              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.3              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.3              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.3              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.0              pyhd8ed1ab_0    conda-forge
nc-time-axis              1.4.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.1           nompi_py310h55e1e36_101    conda-forge
notebook                  6.5.2              pyha770c72_1    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numba                     0.56.3          py310ha5257ce_0    conda-forge
numpy                     1.23.4          py310h53a5b5f_1    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1s               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.5.1           py310h769672d_1    conda-forge
pandoc                    2.19.2               h32600fe_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h454ad03_3    conda-forge
pint                      0.19.2             pyhd8ed1ab_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
proj                      9.1.0                h93bde94_0    conda-forge
prometheus_client         0.15.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.32             pyha770c72_0    conda-forge
properscoring             0.1                        py_0    conda-forge
psutil                    5.9.4           py310h5764c6d_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio                14.0                h0d2025b_11    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.4.0           py310hb1338dc_2    conda-forge
pyqt                      5.15.7          py310h29803b5_2    conda-forge
pyqt5-sip                 12.11.0         py310hd8f1fbe_2    conda-forge
pyrsistent                0.19.2          py310h5764c6d_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
pyzmq                     24.0.1          py310h330234f_1    conda-forge
qt-main                   5.15.6               hd477bba_1    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scikit-learn              1.1.3           py310h0c3af53_1    conda-forge
scipy                     1.9.3           py310hdfbd76f_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
shapely                   1.8.5           py310h5e49deb_1    conda-forge
sip                       6.7.4           py310hd8f1fbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.4               h4ff8645_0    conda-forge
stack_data                0.6.0              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.17.0             pyh41d4057_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.1             py310h5764c6d_3    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022f                h191b570_0    conda-forge
unicodedata2              15.0.0          py310h5764c6d_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
uxarray                   2022.11.0          pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.4.2              pyhd8ed1ab_0    conda-forge
wheel                     0.38.2             pyhd8ed1ab_0    conda-forge
xarray                    2022.11.0          pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xhistogram                0.3.2              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xskillscore               0.0.24             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

**Comment by erogluorhan** [comment]
Thanks very much, @ahijevyc ! Hi @philipc2 , have you experienced anything similar to this before?

**Comment by philipc2** [comment]
Thank you for bringing this to our attention @ahijevyc !

@erogluorhan 

I haven't run into this issue before, however I presume it's due to us not having direct support for identifying MPAS mesh files in `ux.parse_grid()`, since its neither a SCRIP, EXODUS, Shape, or UGRID type.

There are ways to convert from MPAS to SCRIP (see the [mpas_tools](http://mpas-dev.github.io/MPAS-Tools/0.1.0/_modules/mpas_tools/scrip/from_mpas.html) docs). I will look into it this week, however having a direct MPAS to UGRID function would also be of value.

**Comment by philipc2** [comment]
Hi @ahijevyc 

One workaround is to convert from MPAS to SCRIP to UGRID, since UXarray supports the SCRIP format. 

I've looked into the dataset you provided a bit further and attempted to convert it to a SCRIP file using `mpas_tools`. There are a couple issues I'd like to highlight
1. `lonVertex` is currently in the range [-pi, pi] instead of [0, 2pi]
2. Missing `areaCell` variable 

Issue 1 is easily resolved by adding pi to `lonVertex`, however the lack of an `areaCell` variable prevents the conversion to SCRIP from occurring. I attempted to remove any reference to `areaCell` from the MPAS to SCRIP function, however this prevented the conversion to the UGRID conventions in UXarray. 

Do you have another subset of the dataset that includes the `areaCell` variable? I've collected some of my work (including another MPAS dataset) in this repo https://github.com/NCAR/geocat-scratch/tree/main/uxarray-mpas

Let me know if you have any questions as I'll be working on this topic

**Comment by ahijevyc** [comment]
Hi @philipc2 , 
Yes, perhaps you can use /glade/scratch/ahijevyc/nystrom/CNTL/2005082500/x1.2621442.grid.nc
It has areaCell and lonVertex in the range [0, 2pi]

Dave

**Comment by ahijevyc** [comment]
Hi @philipc2 <https://github.com/philipc2> ,
Yes, perhaps you can use /glade/scratch/ahijevyc/nystrom/CNTL/2005082500/
x1.2621442.grid.nc
It has areaCell and lonVertex in the range [0, 2pi]

Dave

**Comment by philipc2** [comment]
@ahijevyc 

Hi Dave. I still have to convert the lonVertex to [0, 2pi], however I was able to successfully create a UXarray grid object with the conversion. The notebook in the above repository has been updated.

I'll be working on getting direct support for reading in MPAS files with UXarray in the coming week or two. I'll ping you in the PR when it's ready

**Comment by ahijevyc** [comment]
Hi Philip,
Sorry for the confusion! You are right about the lonVertex range being
[-pi, pi]. Must have been looking at lonCell. For some reason its range is
[0,2pi]
I'll check out the notebook you updated.
