### ISSUE TITLE
cupy instead of dask?

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#177]
JIT and dask have worked fine for us so far. During my meetings at SC 2022 @anissa111  and some recent developments it has come to light that cupy might be a good long term alternative to dask.

It would be good to have a small prototype and discussion on if this options should be explored.

**Comment by erogluorhan** [comment]
So GPU instead of CPU parallelization, or compatibility with both maybe? I am happy to discuss this further.

**Comment by rljacob** [comment]
It looks like cupy is for on-node parallelim within a gpu while dask is task-parallelism across cpu nodes).  So one is not a replacement for the other.  What am I missing?

Does cupy only target NVIDIA Gpus?   There are 2 others that DOE at least needs to support.
