### ISSUE TITLE
Provide an example that shows how to apply Xarray operators to UXarray grids

### ISSUE THREAD

**Issue by clyne** [UXARRAY/uxarray#181]
It would be useful to have an example (or documentation) showing how Xarray operators that do not require mesh information (such as min or max) can be applied to a UXarray grid.

**Comment by zarzycki** [comment]
To clarify, the idea is to provide an example of using uxarray to...

1. Open a file and read a field on an unstructured grid (say, surface temperature contained in a NetCDF output from MPAS)
2. Print a global maximum or minimum (say 321.1 K and 260.2 K).

Or something more?

**Comment by philipc2** [comment]
Adressed in #216 with the refactor of the following [usage example](https://uxarray.readthedocs.io/en/latest/examples/001-working-with-unstructured-grids.html)
