### ISSUE TITLE
Support visualization of ne120 grids

### ISSUE THREAD

**Issue by TeaganKing** [UXARRAY/uxarray#183]
Hello,

I would be very interested in a feature within the scientific Python ecosystem that would allow users to remap from an CAM SE ne120 grid with time x ncol values to a 0.23x0.31 lat x lon rectilinear grid resulting from a bilinear interpolation. While I have a remapping file that has worked well with ncremap for this purpose, it'd be great to be able to visualize the unstructured data without having to write a netcdf file, remap, and read it back in to visualize (eg, with `ncremap`).

@erogluorhan has mentioned, “despite not having such a visualization functionality implemented yet under UXarray, we have done research and got promising results through our [SIParCS internship project #8](https://www2.cisl.ucar.edu/siparcs-2022-philip-chmielowiec) last summer.” Philip Chmielowiec, who worked on this project, implemented an exploratory visualization stack to directly plot native unstructured grids. The relevant repository can be found [here](https://github.com/NCAR/geocat-scratch/tree/main/polymesh).

@philipc2 also mentioned that “representing CAM-SE grids in the [UGRID conventions](https://ugrid-conventions.github.io/ugrid-conventions/) would be one way of getting the necessary connectivity information for visualization.”

An example original file is located at: /glade/scratch/tking/cgnet/tmq.nc , the corresponding regridded file is: /glade/scratch/tking/cgnet/tmq_regrid.nc , and the mapping file I used is: /glade/campaign/cgd/amp/jet/ClimateNet/data_processing/maps/map_ne120_to_0.23x0.31_bilinear.nc

I have been working on this project with @katiedagon and @jtruesdal , so I’m tagging them here as well!

**Comment by rljacob** [comment]
For visualizing unstructured data, have you tried ncvis?  https://github.com/SEATStandards/ncvis

**Comment by zarzycki** [comment]
Agree with ncvis suggestion for rapid visualization (e.g., when model is running).

Another option is https://geocat-examples.readthedocs.io/en/latest/gallery-notebooks/Datashader/MPAS_Datashader_Trimesh.html

Admittedly, I haven't used it beyond the tutorial above, but student @cdeciampa has used it in her Python workflow for visualizing 3km CAM-MPAS data and 28km CAM-SE data (so ne120, albeit variable-resolution) and may have thoughts.

**Comment by katiedagon** [comment]
Thanks @zarzycki for chiming in! Any examples with CAM-SE would be great to see. I feel like there should be a way to read in the mapping file and use that information to go from ncol to lat/lon, but I haven't been able to figure it out myself.

**Comment by katiedagon** [comment]
Thanks @cdeciampa, that sounds useful! For the work @TeaganKing mentioned I think some smoothing is ok because we primarily want to be able to do some quick visualization checks while we're processing CAM-SE variables. 

I may also take a closer look at [polymesh](https://github.com/NCAR/geocat-scratch/tree/main/polymesh) from @philipc2, though it would be great to have something that works with matplotlib or built-in xarray plotting functionality. It sounds like this is in the works for [uxarray](https://github.com/UXARRAY/uxarray/issues/118).

**Comment by cdeciampa** [comment]
```
import numpy as np
import pandas as pd
import dask.dataframe as dd
from scipy.spatial import Delaunay

import holoviews as hv
from holoviews import opts

import geoviews as gv
import geoviews.feature as gf

import datashader as ds
from holoviews.operation.datashader import rasterize as hds_rasterize
from holoviews.operation.datashader import datashade as hds_datashade

hv.extension("bokeh","matplotlib")

opts.defaults(
    opts.Image(width=1200, height=600),
    opts.RGB(width=1200, height=600))
```

```
def triangulate(vertices, x="Longitude", y="Latitude"):
    """
    Generate a triangular mesh for the given x,y,z vertices, using Delaunay triangulation.
    For large n, typically results in about double the number of triangles as vertices.
    """
    triang = Delaunay(vertices[[x,y]].values)
    print('Given', len(vertices), "vertices, created", len(triang.simplices), 'triangles.')
    
    tris_df = pd.DataFrame(triang.simplices, columns=['v0', 'v1', 'v2'])
    
    return tris_df
```
```
def createHVTriMesh(x, y, var, var_name, n_workers=1):
    # Declare verts array
    # This is essentally an XYZ matrix (at the location of x and y, z=?) 3 X len(verts) array
    verts = np.column_stack([x, y, var])

    # Convert to pandas
    verts_df  = pd.DataFrame(verts,  columns=['Longitude', 'Latitude', var_name])
    
    # Creates Delaunay triangular mesh
    tris_df = triangulate(verts_df)

    # Convert to dask, nworkers is for parallelization (not yet implemented)
    verts_ddf = dd.from_pandas(verts_df, npartitions=n_workers)
    tris_ddf = dd.from_pandas(tris_df, npartitions=n_workers)

    # Declare HoloViews element
    tri_nodes = hv.Nodes(verts_ddf, ['Longitude', 'Latitude', 'index'], [var_name])
    trimesh = hv.TriMesh((tris_ddf, tri_nodes))
    return(trimesh)
```
```
# My 'h3p' data is 3-hourly and contains non-mesh data.
h3p_files = glob.glob(os.path.join(parent_28km, '*.h3.*.nc'))
h3pn_ds = xr.open_mfdataset([f for f in h3p_files if 'remap' not in f], parallel=True)

# This is the CAMSE mesh file.
p_mesh = "/path/to/ne0np4natlanticext.ne30x4.g_scrip.nc"
p_mesh_ds = xr.open_dataset(p_mesh)
```
```
# Extracts grid centerpoints from CAMSE mesh
lonCell = p_mesh_ds.grid_center_lon.values
latCell = p_mesh_ds.grid_center_lat.values
lonCell = ((lonCell - 180.0) % 360.0) - 180.0

# Selects target variable and target time from xarray dataset
sel_time = 23
var = 'FLUT'
primalVar = h3pn_ds[var].isel(time=sel_time).values

# Creates triangular mesh from CAMSE grid + data using Delaunay triangulation and HoloViews TriMesh
trimesh = createHVTriMesh(lonCell, latCell, primalVar, var)
```
```
# Retrieves plotting bounding box (custom function for my research to locate TCs)
lon_range, lat_range = find_TC_bbox(h3pn_ds, 'florida', sel_time, center_dist=1000)

# If you want to project coordinates (currently my only functioning workflow)
proj = ccrs.Robinson(central_longitude=0.0)
xPCS, yPCS, _ = proj.transform_points(ccrs.PlateCarree(), lonCell, latCell).T
x_range, y_range, _ = proj.transform_points(ccrs.PlateCarree(), np.array(lon_range), 
np.array(lat_range)).T
lon_range = tuple(x_range)
lat_range = tuple(y_range)

# This uses Datashader to take the triangular mesh and rasterizes it
rasterized = hds_rasterize(trimesh, aggregator='mean', precompute=True, x_range=lon_range, 
y_range=lat_range, vdim_prefix='')

# Plots the rasterized data, which uses Bokeh as its underlying plotting package
cam_native_olr = rasterized.opts(tools=['hover'], colorbar=True, cmap=flut_cimss, 
title='CAM5 (Native) Upwelling Longwave Flux', clim=(50, 650), width=1000, 
height=900, clabel='Upwelling Longwave Flux [W/m^2]', colorbar_position='bottom', 
fontsize=dict(title='36pt', clabel='30pt', cticks='28pt')) *\
gf.coastline(projection=proj).options(scale='10m')

# Can either plot right in a jupyter notebook by calling 'cam_native_olr' or save to a file:
hv.save(cam_native_olr, '../figs/cam_native_olr.png', fmt='png')
```

I suspect that where I make the triangular mesh, I can use [HoloViews' QuadMesh](https://holoviews.org/reference/elements/bokeh/QuadMesh.html#irregular-meshes) in its place for a more appropriate workflow for CAMSE, but I haven't been able to implement that yet. I heavily built my code off the MPAS Datashader notebook that @zarzycki linked above, but please let me know if anything's unclear.

**Comment by chengzhuzhang** [comment]
Appreciate all the useful information provided in this discussion! I was in the same boat to be able to visualize the  ne30/ne120 E3SM simulation data in a Python environment. The best approach that was identified within E3SM is the script wrote by @ambrad. 
The python script prepares the native grid data for `matplotlib` patches. https://github.com/ambrad/scream-docs/blob/diags-dev/diags/native_grid.py @ambrad hope you don't mind that I post your script here :). 
It would be nice to get a solution through `uxarray`

**Comment by zarzycki** [comment]
OK, probably what I *shouldn't* have been doing this afternoon, but... I've come around on @vijaysm's solution from https://github.com/UXARRAY/uxarray/issues/172

I think what @TeaganKing (and perhaps @katiedagon) were mentioning above was using an ESMF weight file to go SE -> structured (FV). While this can be done with e.g., `ncremap` it's not ideal to be carrying around multiple data files with redundant information.

So if one has a weight file pre-computed, the below should work.

```
import numpy as np
import scipy as sp
import xarray as xr
import matplotlib.pyplot as plt

## Open netCDF data on unstructured mesh
datafile='FHIST-ne30-ATOMIC-ERA5-x001_INIC.nc'
xdf=xr.open_dataset(datafile)

## ESMF weightfile
filename='map_ne30_to_1x1glob_patch.nc'
xwgt=xr.open_dataset(filename)
srclat=xwgt['yc_a']
srclon=xwgt['xc_a']
dstlat=xwgt['yc_b']
dstlon=xwgt['xc_b']
src_grid_dims=xwgt['src_grid_dims'].values
dst_grid_dims=xwgt['dst_grid_dims'].values

print("Src grid dims: {0}, dst grid dims: {1}".format(src_grid_dims, dst_grid_dims))

n_a = xwgt['n_a'].size # col dimension
n_b = xwgt['n_b'].size # row dimension
n_s = xwgt['n_s'].size # nnz dimension

print("Map contains {0} rows, {1} cols and {2} nnz values".format(n_b, n_a, n_s))

rows = xwgt['row'][:] - 1 # row indices (1-based)
cols = xwgt['col'][:] - 1 # col indices (1-based)
nnzvals = xwgt['S'][:] # nnz map values

## Create sparse matrix map
map = sp.sparse.coo_matrix((nnzvals, (rows,cols)),shape=(n_b,n_a))

## Now apply map onto a src column vector length n_a to compute vector length n_b
field_target = map @ xdf.PS[0,:].values 

## Reshape 1-D vector returned to dst_grid_dims
data_out = np.reshape(field_target, dst_grid_dims, order='F')

print("Reshaped array now has dimensions {0}".format(dst_grid_dims, n_a, n_s))

## Reshape destination grid to build structured xarray da
lat2d = np.reshape(dstlat.values, dst_grid_dims, order='F')
lon2d = np.reshape(dstlon.values, dst_grid_dims, order='F')

## Build da
da = xr.DataArray(
    data=data_out,
    dims=["x", "y"],
    coords=dict(
        lon=(["x"], lon2d[:,0]),
        lat=(["y"], lat2d[0,:]),
    )
)

## Simple plot
da.plot(x="lon", y="lat")
```

![Screen Shot 2022-12-08 at 4 12 33 PM](https://user-images.githubusercontent.com/10341827/206570962-a5d75532-9993-4940-905f-50de2d7619a4.png)

**Comment by katiedagon** [comment]
Thanks @cdeciampa @zarzycki this is great! Extracting the grid information from the pre-computed ESMF weight file is what I was looking for, so that's a huge help. @TeaganKing I already tested this on some of our data and it works 🎉 

As @dcherian has mentioned to me in the past, this is probable also doable with xESMF as in pangeo-data/xESMF#202.

**Comment by dcherian** [comment]
> As @dcherian has mentioned to me in the past, this is probable also doable with xESMF as in https://github.com/pangeo-data/xESMF/issues/202

I actually got pretty close during the ESDS hackathon with Christine Shields. I'll try and write it up as a blogpost this evening.

**Comment by katiedagon** [comment]
> Appreciate all the useful information provided in this discussion! I was in the same boat to be able to visualize the ne30/ne120 E3SM simulation data in a Python environment. The best approach that was identified within E3SM is the script wrote by @ambrad. The python script prepares the native grid data for `matplotlib` patches. https://github.com/ambrad/scream-docs/blob/diags-dev/diags/native_grid.py @ambrad hope you don't mind that I post your script here :). It would be nice to get a solution through `uxarray`

@chengzhuzhang I think that links to a private repo, at least I can't see anything. Good to have multiple options though!

**Comment by zarzycki** [comment]
Yes, I also tried to get this work with xESMF based on @dcherian's comment (I am curious to see your hackathon results!)...

What I found relatively tricky is that a lot of the xESMF abstraction appeared to rely on labeled/structured input and structured output (even if the mapping is not structured, it wants to read lat/lon coordinate data from the input DataArray). So I couldn't get the above to work with xESMF out of the box without a lot of hacky dimension expansion and reordering so I figured it was just easier to directly apply the weights mathematically. I'm sure there is probably a way to massage the inputs I didn't think of...

Plus, the 15 years I invested becoming an NCL black belt mean my immediate kneejerk reaction is to find (frequently convoluted) ways to minimize dependencies. ;)

**Comment by ambrad** [comment]
> @chengzhuzhang I think that links to a private repo, at least I can't see anything. Good to have multiple options though!

Here's a link to a gist of that code: https://gist.github.com/ambrad/4e574880843a7ee6e8ca55c4461daefb

**Comment by philipc2** [comment]
Adding to the comment in the main body of this post.

Based off my work and research from this summer, one of the most promising ways to visualize unstructured grids is to represent in a format that is compatible with the HoloViz stack (Datashader, GeoViews, etc). As highlighted in the GeoCAT MPAS Visualization example, one way is to triangulate our grid and visualize it that way. However, this method requires us to restructured our original grid into a mesh of triangles, which can lead to some unwanted side-effects. 

Unstructured Grids can be represented as Polygons, which would create a direct representation of each face in our grid. At the most basic representation, this only requires three UGRID variables (Mesh2_node_x, Mesh2_node_y, and Mesh2_face_nodes). Once we have our grid represented in polygon form, we can render it using Datashader and GeoViews. Datashader also has support for rasterization, which would essentially map our mesh of polygons to a structrued grid at the visualization step, removing the need to create separate files. 

With this in mind, having a function that encodes any input grid format into UGRID would create the necessary connectivity information needed for this visualization work. The main benefit would be that it's very Pythonic in nature, utilizing only a handful of libraries to get the job done, most of which can be abstracted with UXarray functions (Polygon creation, etc.)

I've attached a couple figures from my AGU poster on this topic. I'll be presenting this poster on Wednesday from 2:45 to 6:15 at AGU for anyone interested in discussing this in person.



![image](https://user-images.githubusercontent.com/67855069/206618875-e73cda01-6722-4a0f-907c-e762b6d46046.png)


# Visualization Example
![image](https://user-images.githubusercontent.com/67855069/206619232-517ca78d-298f-46ef-ada1-682ec68a307b.png)

**Comment by cdeciampa** [comment]
@philipc2 thank you for this! I also use MPAS for my research and have been wondering how I could better leverage HoloViews to visualize its native icosahedral mesh.

**Comment by dcherian** [comment]
Here's a rough post: https://github.com/NCAR/esds/pull/217

Comments and  suggestions welcome!

**Comment by zarzycki** [comment]
> Based off my work and research from this summer, one of the most promising ways to visualize unstructured grids is to represent it in a format that is compatible with the HoloViz stack (Datashader, GeoViews, etc). As highlighted in the GeoCAT MPAS Visualization example, one way is to triangulate our grid and visualize it that way. However, this method requires us to restructured our original grid into a mesh of triangles, which can lead to some unwanted side-effects.
>
> (CZ snip)

This is great, @philipc2 I'll try to catch your poster at AGU.

FWIW, this type of visualization (avoiding Delauney etc. and leveraging the cell boundaries) I think is what @whannah1 and @adamrher et al., were discussing in https://github.com/UXARRAY/uxarray/discussions/46#discussioncomment-2747480 and https://github.com/UXARRAY/uxarray/discussions/46#discussioncomment-2751225 and https://github.com/UXARRAY/uxarray/discussions/46#discussioncomment-2778125, which garnered a lot of good back-and-forth. I think being able to plot the underlying topology as a series of polygons will be tremendously helpful on the model development size, where actually visualizing what is going on at the discrete element level may be important (numerical noise, since column instability, etc.)

**Comment by TeaganKing** [comment]
Thanks everyone for this great discussion and all of your suggestions! This is really helpful to see how you used the ESMF weight file to obtain grid information, @zarzycki and @katiedagon ! @dcherian , your notebook is also really clear and it's good to have an option of using `xesmf.Regridder()`!

**Comment by katiedagon** [comment]
Relevant to this discussion, The [NCAR Earth System Data Science (ESDS)](https://ncar.github.io/esds/) initiative is organizing an upcoming collaborative work session on “Working with Unstructured Grids". Collaborators external to NCAR/UCAR are very welcome.

MORE INFO: See this [Google Doc](https://docs.google.com/document/d/1WMDosSVchC9tt7xac90sUekP6nJef6yRDizolr4SVZo/edit#).

**Comment by philipc2** [comment]
Closing this issue since we've already demonstrated the capability to visualize these grids. 

https://projectpythia.org/unstructured-grid-viz-cookbook/README.html
