### ISSUE TITLE
Add a roadmap to the "Community" menu on UXarray website

### ISSUE THREAD

**Issue by anissa111** [UXARRAY/uxarray#184]
See https://github.com/NCAR/projectraijin.github.io/issues/6

**Comment by erogluorhan** [comment]
Is this a duplicate with #182 ?

**Comment by anissa111** [comment]
@erogluorhan Yeah, I think it might be. I think here I was specifying adding the info to the documentation, but both issues are trying to express the same end goal I believe

**Comment by anissa111** [comment]
Closing as duplicate

**Comment by anissa111** [comment]
Closing as duplicate
