### ISSUE TITLE
The current data read-in will make the FillValue=nan instead of -1

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#189]
Our current implementation to construct Grid from 
```
xr_tgrid1 = xr.open_dataset(str(ug_filename1))
tgrid1 = ux.Grid(xr_tgrid1)

```
According to our API documentation, the `uxarray.Grid.Mesh2_face_nodes` should have the following properties
> uxarray.Grid.Mesh2_face_nodes: integer DataArray of size (nMesh2_face, MaxNumNodesPerFace)
> A DataArray of indices for each face node, corresponding to coordinates in uxarray.Grid.node_*. Faces can have arbitrary length, with _FillValue=-1 used when faces have fewer nodes than MaxNumNodesPerFace. Nodes are in counter-clockwise order.

However, the current Grid construction will make the _FillValue=nan instead of -1. This already caused a malfunction in my implemented `build_edge_face_connectivity` which I will take care of later. But such inconsistency might bring more problems in the following code developments

**Comment by erogluorhan** [comment]
Thanks! I think defaulting to NaN is better than to -1, so we need to change the draft API doc. Is it also what you meant to fix the inconsistency?

**Comment by paullric** [comment]
Why do you think defaulting to NaN is better than to -1?

_FillValue = nan is notorious for breaking things, though perhaps that is a legacy issue.

**Comment by erogluorhan** [comment]
I'd say, 
- NaN is consistently used for missing data representation in Python, 
- `np.nan` could enable vectorized execution and hence I'd expect improved performance
- I also personally like the fact that `-1 == -1` is true but `NaN == NaN` is false, which would be useful for cases such as comparing indices, etc. 
- Despite not applicable to the case here (i.e. -1 can never be an index), using particular values for missing data might lead to not-breaking but wrong-executing codes.

Though, NaN might be converting the data arrays it resides in to floating point even if they are integer (which is this case since we are working on index numbers). I don't know if this'd be an issue.

**Comment by hongyuchen1030** [comment]
> Thanks! I think defaulting to NaN is better than to -1, so we need to change the draft API doc. Is it also what you meant to fix the inconsistency?

Yes. I was just saying no matter what kind of FillValue we choose finally, it's better to have a clear description in the documentation so that we can base the following development on that.

Currently, I have considered FillValue = -1 and nan in my following implementation to eliminate possible marginal cases.

**Comment by rljacob** [comment]
What happens when a Netcdf data set we read has missing values?  Are they converted to NaN?

**Comment by philipc2** [comment]
Another issue with using `-1`  is that it corresponds to the last value in an array if used as an index. For example, if a row in `Mesh2_face_nodes` consists of indices $[1, 2, 3, -1, -1, -1]$, attempting to use this as an index into `Mesh2_node_x` would return a total of six values, with the final 3 being the last value in `Mesh2_node_x`. 

Using `NaN` would prevent this from happening and would raise IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices.

**Comment by philipc2** [comment]
Another possible solution would be to use Numpy Masked Arrays to handle the Fill Values

https://numpy.org/doc/stable/reference/maskedarray.generic.html#what-is-a-masked-array
https://numpy.org/doc/stable/reference/maskedarray.generic.html#examples

**Comment by rljacob** [comment]
Seems like xarray would already have a solution for this.

**Comment by philipc2** [comment]
> Seems like xarray would already have a solution for this.

Appears that they use NaN's when handling missing values. 

https://xarray.pydata.org/en/v0.10.4/computation.html#missing-values

**Comment by rljacob** [comment]
After reading [masked arrays](https://github.com/pydata/xarray/issues/1194) it appears that "NaN instead of -1" is a symptom of a different problem:  if you try to create an integer array and there are masked values, the array gets promoted to float and the missing values to NaN.

**Comment by philipc2** [comment]
To clarify what I stated above, using an integer `_FillValue` in the range `[-nMesh2_node, nMesh2_node)` in a mixed-topology scenario could lead to indexing/slicing issues, since the `_FillValue` would be a valid index into `Mesh2_node_x` for a lower-dimension geometry (triangle vs polygon) with negative indexing and slicing in arrays. 

In theory, having `NaN` values would prevent users from indexing using the full slice for a lower dimension geometry, however this would require us to convert our array into floats, which isn't ideal for `Mesh2_face_nodes` since they should be represented as integers. 

#162 also set our default datatype for `Mesh2_face_nodes` to `uint32`, restricting us to natural integers. Behind the hood, we could represent our `_FillValue` as the largest possible maximum integer for whichever data type we chose, since it is VERY unlikely we will every have more than the max int number of nodes. This would allow us to keep `Mesh2_face_nodes` as unsigned integers and prevent improper indexing for users that attempt to slice using a mixed-topology grid. 

Much of the indexing issues could be resolved by knowing the dimension of each face, however this discussion merits its own issue.

**Comment by rljacob** [comment]
Are you sure UGRID allows negative numbers to be used for indexing nodes?

**Comment by philipc2** [comment]
> Are you sure UGRID allows negative numbers to be used for indexing nodes?

I'm certain UGRID doesn't, however when not handled properly in Python, negative numbers index from the end of the array.

**Comment by paullric** [comment]
In the UGRID conventions document, indices are stored as integers, which would suggest negative values are allowed.

https://ugrid-conventions.github.io/ugrid-conventions/#2d-flexible-mesh-mixed-triangles-quadrilaterals-etc-topology <https://ugrid-conventions.github.io/ugrid-conventions/#2d-flexible-mesh-mixed-triangles-quadrilaterals-etc-topology>

Curiously Mesh2_face_nodes uses a _FillValue of 999999 while Mesh2_face_links uses a _FillValue of -999.

**Comment by rljacob** [comment]
Technically allowed but is there any practical reason to index nodes in a mesh with negative numbers?

**Comment by hongyuchen1030** [comment]
> To clarify what I stated above, using an integer `_FillValue` in the range `[-nMesh2_node, nMesh2_node)` in a mixed-topology scenario could lead to indexing/slicing issues, since the `_FillValue` would be a valid index into `Mesh2_node_x` for a lower-dimension geometry (triangle vs polygon) with negative indexing and slicing in arrays.
> 
> In theory, having `NaN` values would prevent users from indexing using the full slice for a lower dimension geometry, however this would require us to convert our array into floats, which isn't ideal for `Mesh2_face_nodes` since they should be represented as integers.
> 
> #162 also set our default datatype for `Mesh2_face_nodes` to `uint32`, restricting us to natural integers. Behind the hood, we could represent our `_FillValue` as the largest possible maximum integer for whichever data type we chose, since it is VERY unlikely we will every have more than the max int number of nodes. This would allow us to keep `Mesh2_face_nodes` as unsigned integers and prevent improper indexing for users that attempt to slice using a mixed-topology grid.
> 
> Much of the indexing issues could be resolved by knowing the dimension of each face, however, this discussion merits its own issue.

I think the concern about the `_FillValue_=-1` might cause indexing errors can be solved by checking whether the index is positive every time we need to find the node index. 

Because in the end, although the possibility is low, the node number might still reach the `MAX` number (This is also a marginal case we need to consider about in the future).  In another word, either using the `_FillValue_=-1` or `_FillValue_=MAX`, it's always ideal to do a precheck when we call the indexing.

**Comment by hongyuchen1030** [comment]
In the https://github.com/UXARRAY/uxarray/blob/b4c002ac8f0d561cf446380b00bc66ecab653c6d/uxarray/_exodus.py#L10
We are defining "_FillValue" -1, while the actually _FillValue read-in now is `np.nan`, also the actual `ds["Mesh2_face_nodes"]` is a float array instead of the `integer array` 

>     # outside the k,v for loop
>     # set the face nodes data compiled in "connect" section
>     ds["Mesh2_face_nodes"] = xr.DataArray(
>         data=(conn[:] - 1),
>         dims=["nMesh2_face", "nMaxMesh2_face_nodes"],
>         attrs={
>             "cf_role":
>                 "face_node_connectivity",
>             "_FillValue":
>                 -1,
>             "start_index":
>                 int_dtype(
>                     0)  # NOTE: This might cause an error if numbering has holes
>         })

**Comment by erogluorhan** [comment]
> 



> > To clarify what I stated above, using an integer `_FillValue` in the range `[-nMesh2_node, nMesh2_node)` in a mixed-topology scenario could lead to indexing/slicing issues, since the `_FillValue` would be a valid index into `Mesh2_node_x` for a lower-dimension geometry (triangle vs polygon) with negative indexing and slicing in arrays.
> > In theory, having `NaN` values would prevent users from indexing using the full slice for a lower dimension geometry, however this would require us to convert our array into floats, which isn't ideal for `Mesh2_face_nodes` since they should be represented as integers.
> > #162 also set our default datatype for `Mesh2_face_nodes` to `uint32`, restricting us to natural integers. Behind the hood, we could represent our `_FillValue` as the largest possible maximum integer for whichever data type we chose, since it is VERY unlikely we will every have more than the max int number of nodes. This would allow us to keep `Mesh2_face_nodes` as unsigned integers and prevent improper indexing for users that attempt to slice using a mixed-topology grid.
> > Much of the indexing issues could be resolved by knowing the dimension of each face, however, this discussion merits its own issue.
> 
> I think the concern about the `_FillValue_=-1` might cause indexing errors can be solved by checking whether the index is positive every time we need to find the node index.
> 
> Because in the end, although the possibility is low, the node number might still reach the `MAX` number (This is also a marginal case we need to consider about in the future). In another word, either using the `_FillValue_=-1` or `_FillValue_=MAX`, it's always ideal to do a precheck when we call the indexing.

Well, I am not sure about this when it is Python as this language natively supports negative indexing and it could be useful in ways that @philipc2 described in a prior review comment. I'd agree with fixing with negative index checking if it was C, C++, etc., but in Python I feel that shouldn't be the way to go. Using `dtype`'s MAX sounds reasonable to me as we used that approach in a [prior implementation](https://github.com/NCAR/geocat-f2py/blob/main/src/geocat/f2py/missing_values.py) somewhere else, but we should explore other viable implementations, too.

**Comment by hongyuchen1030** [comment]
> > 
> 
> > > To clarify what I stated above, using an integer `_FillValue` in the range `[-nMesh2_node, nMesh2_node)` in a mixed-topology scenario could lead to indexing/slicing issues, since the `_FillValue` would be a valid index into `Mesh2_node_x` for a lower-dimension geometry (triangle vs polygon) with negative indexing and slicing in arrays.
> > > In theory, having `NaN` values would prevent users from indexing using the full slice for a lower dimension geometry, however this would require us to convert our array into floats, which isn't ideal for `Mesh2_face_nodes` since they should be represented as integers.
> > > #162 also set our default datatype for `Mesh2_face_nodes` to `uint32`, restricting us to natural integers. Behind the hood, we could represent our `_FillValue` as the largest possible maximum integer for whichever data type we chose, since it is VERY unlikely we will every have more than the max int number of nodes. This would allow us to keep `Mesh2_face_nodes` as unsigned integers and prevent improper indexing for users that attempt to slice using a mixed-topology grid.
> > > Much of the indexing issues could be resolved by knowing the dimension of each face, however, this discussion merits its own issue.
> > 
> > 
> > I think the concern about the `_FillValue_=-1` might cause indexing errors can be solved by checking whether the index is positive every time we need to find the node index.
> > Because in the end, although the possibility is low, the node number might still reach the `MAX` number (This is also a marginal case we need to consider about in the future). In another word, either using the `_FillValue_=-1` or `_FillValue_=MAX`, it's always ideal to do a precheck when we call the indexing.
> 
> Well, I am not sure about this when it is Python as this language natively supports negative indexing and it could be useful in ways that @philipc2 described in a prior review comment. I'd agree with fixing with negative index checking if it was C, C++, etc., but in Python I feel that shouldn't be the way to go. Using `dtype`'s MAX sounds reasonable to me as we used that approach in a [prior implementation](https://github.com/NCAR/geocat-f2py/blob/main/src/geocat/f2py/missing_values.py) somewhere else, but we should explore other viable implementations, too.

My point is, the `_Fill_Value` should be a value we will never use for indexing. And we cannot eliminate the possibility about the index might reach to `dtype`'s MAX so far. So even if we use `dtype`'s MAX, a pre-check function is also recommended for robustness.

**Comment by erogluorhan** [comment]
> > Well, I am not sure about this when it is Python as this language natively supports negative indexing and it could be useful in ways that @philipc2 described in a prior review comment. I'd agree with fixing with negative index checking if it was C, C++, etc., but in Python I feel that shouldn't be the way to go. Using `dtype`'s MAX sounds reasonable to me as we used that approach in a [prior implementation](https://github.com/NCAR/geocat-f2py/blob/main/src/geocat/f2py/missing_values.py) somewhere else, but we should explore other viable implementations, too.
> 
> My point is, the `_Fill_Value` should be a value we will never use for indexing. And we cannot eliminate the possibility about the index might reach to `dtype`'s MAX so far. So even if we use `dtype`'s MAX, a pre-check function is also recommended for robustness.

That's also reasonable, but I'd think, in practice, it should be almost impossible for index to reach the MAX even though it is technically possible. Because of the technical possibility though, I suggest we look into other good implementations about FillValue. Do we know any such implementations in Python as a reference?

**Comment by philipc2** [comment]
@erogluorhan 

I agree that in practice, we will rarely (if ever) reach the limits of `uint32` or `uint64` when working with `Mesh2_face_nodes`. If we need more precision that `uint32`, we can use `uint64` 

We need to have a standardized `dtype` for `Mesh2_face_nodes` (and other variables) that is defined at the data loading step. Using a consistent datatype throughout our code would allow us to assign a `_FillValue` that ensures no conflicts. 

This would avoid the need for users to run the following and accidently clobber any negative fill values:
```Python
# typically fine 
face_nodes = ugrid.Mesh2_face_nodes.astype(int)
# if we use a negative fill value, it would be clobbered
face_nodes = ugrid.Mesh2_face_nodes.astype(np.uint32)
```
There is also the option to use `np.intp` which is described [here](https://numpy.org/doc/stable/user/basics.indexing.html#:~:text=The%20native%20NumPy%20indexing%20type%20is%20intp%20and%20may%20differ%20from%20the%20default%20integer%20array%20type.%20intp%20is%20the%20smallest%20data%20type%20sufficient%20to%20safely%20index%20any%20array%3B%20for%20advanced%20indexing%20it%20may%20be%20faster%20than%20other%20types.). `xugrid` uses this as their default integer datatype and @hongyuchen1030 has worked with this in one of her recent PR's. There is also `np.uintp` which is the unsigned equivalent. The downside of this route is that it takes on the largest integer defined by the system, which may not be necessary for datasets that fit into a 32bit integer.

### My Take

* Create a `constants.py` or equivalent file to maintain default datatypes for variables
* Set the default `dtype` as `uint32`, with `uint64` used for extra precession, for variables that are used for integer indexing (`Mesh2_face_nodes`, etc.)
* Other default types can be discussed in a separate issue
* Define `_FillValue32` as the max value of `uint32` and Define `_FillValue64` as the max value of `uint64`
* At the data loading step, use the appropriate integer data type (`uint32` or `uint64`) and their corresponding `_FillValue`. This would handle loading in either 32-bit or 64-bit datasets.
* Replace the instances of the original `_FillValue` if one is provided by the one we selected
* Set the `_FillValue` as an attribute within the `Grid` object 
* Define helper functions or additional variables (such as the one is described in #193) to assist with indexing and bookkeeping

Are there any objections to this? This should eliminate the case of the index reaching the max of our `dtype`, unless we are reading in an obscenely large dataset. This would be the case where we have use all `0xFFFFFFFFFFFFFFFF` unique values in `uint64` as indices in `Mesh2_face_nodes`, in which case we would be working with datasets on the scale of `exabytes` if my calculations are correct.
