### ISSUE TITLE
Add the build Latlonbound feature

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#204]
The purpose of this issue is to implement the add build_latlonbound feature in the UXArray, which will be placed under the `uxarray/grid.py/Grid.buildlatlon_bounds`

PR #201 contains the necessary helper functions for the function

PR #203 contains the test case as well as its helper functions for the `build_latlonbound`

The implementation of this feature also depends on the successful merge of PR #188  and PR #191 

The main implementation of the `uxarray/grid.py/Grid.buildlatlon_bounds` will be created as a PR after #188, #191 and #201 are all successfully merged since it depends on all three PR

**Comment by hongyuchen1030** [comment]
@anissa111 Can you take a look into my PR #201 to see how to vectorize the codes there, or, how should I reorganize the codes so it will help with my future vectorization usage? Thank you very much.

If you have time, PR #203 is the test case that uses index looping that requires some vectorization.

Thank you very much!

**Comment by anissa111** [comment]
@hongyuchen1030 Yes, I should have some time to look in to this tomorrow!

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030 Yes, I should have some time to look in to this tomorrow!

Thanks!
