### ISSUE TITLE
Organize test files

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#210]
This issue points two things to be fixed with our current test structure:

1. Test files are not organized, and it is hard to follow them through README file. A grid format-based organization would work better (e.g. /ugrid, /ugrid/fesom, /ugrid/geoflow-small, /exoduus, /scrip, etc.).

2. This part has now been moved into a new issue (#212):
~~I believe for any test format/case, the minimal set of files we need to have is a grid topology file along with at least two variable files (just like we currently do with the "outCSne30" or "fesom" cases). However, for many existing test files, we only have a grid topology file, which is not sufficient for testing dataset openning operations (only a grid topology can be opened with that file).~~
   - ~~We need to find and add at least two different variable files for the following cases:~~
      - ~~outCSne8 (does not have any var files)~~
      - ~~outRLL1deg (has only vortex var file)~~
      - ~~ov_RLL10deg_CSne4 (has only vortex var file)~~
      - ~~mesh.nc (does not have any var files)~~

@rajeeja @anissa111

**Comment by rajeeja** [comment]
I will add the var files

**Comment by erogluorhan** [comment]
@rajeeja Would be great! Use #212 for that!
