### ISSUE TITLE
Expand test files

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#212]
As a continuation to Issue #210:

I believe for any test format/case, the minimal set of files we need to have is a grid topology file along with at least two variable files (just like we currently do with the "outCSne30" or "fesom" cases). However, for many existing test files, we only have a grid topology file, which is not sufficient for testing dataset opening operations (only a grid topology can be opened with that file).
   
   - We need to find and add at least two different variable files for the following cases:
      - outCSne8 (does not have any var files)
      - outRLL1deg (has only vortex var file)
      - ov_RLL10deg_CSne4 (has only vortex var file)
      - mesh.nc (does not have any var files)

@rajeeja @anissa111

**Comment by erogluorhan** [comment]
I think we can close this since our existing test files, despite not still satisfying the ask here, have been helpful. Thoughts @rajeeja @philipc2?

**Comment by philipc2** [comment]
> I think we can close this since our existing test files, despite not still satisfying the ask here, have been helpful. Thoughts @rajeeja @philipc2?

Good with me.
