### ISSUE TITLE
Current `Grid._populate_cartesian_xyz_coord` and `Grid._populate_lonlat_coord` is not updated well with the new design

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#223]
Current `Grid._populate_cartesian_xyz_coord` and `Grid._populate_lonlat_coord` are still using the old data structures, though it can pass the testcases, both the `Mesh2_node_cart_x/y/z` and `Mesh2_node_x/y/z` are stored inside `Grid.ds` instead of `Grid`

This issue need to be addressed before the merge of the latlonbox algorithm and zonal average algorithmn

**Comment by philipc2** [comment]
Closing this issue since it should not pose an issue anymore with separate `main` and `redesign` branches
