### ISSUE TITLE
Unable to open UGRID file

### ISSUE THREAD

**Issue by clyne** [UXARRAY/uxarray#27]
I believe that the attached NetCDF grid  file is UGRID compliant, but when I try to open it with:

`uds = ux.open_dataset('grid.nc')
`

I get:

_Loading initial grid from file:  /Users/clyne/Data/UGRID/geoflow-ugrid/small/grid.nc
This is not a supported NetCDF file_

Here is an `ncdump -h` of the file:

netcdf grid {
dimensions:
	nMeshNodes = 6000 ;
	nMeshFaces = 3840 ;
	nFaceNodes = 4 ;
	meshLayers = 20 ;
	time = 1 ;
variables:
	int mesh ;
		mesh:cf_role = "mesh_topology" ;
		mesh:long_name = "Topology data of 2D unstructured mesh." ;
		mesh:topology_dimension = 2 ;
		mesh:node_coordinates = "mesh_node_x mesh_node_y" ;
		mesh:face_node_connectivity = "mesh_face_nodes" ;
		mesh:face_dimension = "nMeshFaces" ;
	uint mesh_face_nodes(nMeshFaces, nFaceNodes) ;
		mesh_face_nodes:cf_role = "face_node_connectivity" ;
		mesh_face_nodes:long_name = "Maps every face to its corner nodes." ;
		mesh_face_nodes:_FillValue = 4294967295U ;
		mesh_face_nodes:start_index = 0 ;
	double mesh_node_x(nMeshNodes) ;
		mesh_node_x:standard_name = "longitude" ;
		mesh_node_x:long_name = "Longitude of 2D mesh nodes." ;
		mesh_node_x:units = "degrees_east" ;
	double mesh_node_y(nMeshNodes) ;
		mesh_node_y:standard_name = "latitude" ;
		mesh_node_y:long_name = "Latitude of 2D mesh nodes." ;
		mesh_node_y:units = "degrees_north" ;
	double mesh_depth(meshLayers, nMeshNodes) ;
		mesh_depth:units = "meters" ;
		mesh_depth:positive = "up" ;
		mesh_depth:standard_name = "elevation" ;
		mesh_depth:mesh = "mesh" ;
		mesh_depth:location = "node" ;
		mesh_depth:coordinates = "mesh_node_x mesh_node_y" ;
}

[grid.nc.gz](https://github.com/UXARRAY/uxarray/files/8336834/grid.nc.gz)

**Comment by rajeeja** [comment]
Thanks for the attachment and this issue.

We're specifically checking for "Mesh2". As ncdump shows it doesn't have that, we throw the error you see. Do you know about varieties/version(s) of ugrid formats?
________________________________
From: clyne ***@***.***>
Sent: Wednesday, March 23, 2022 4:33:31 PM
To: UXARRAY/uxarray ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UXARRAY/uxarray] Unable to open UGRID file (Issue #27)


I believe that the attached NetCDF grid file is UGRID compliant, but when I try to open it with:

uds = ux.open_dataset('grid.nc')

I get:

Loading initial grid from file: /Users/clyne/Data/UGRID/geoflow-ugrid/small/grid.nc
This is not a supported NetCDF file

Here is an ncdump -h of the file:

netcdf grid {
dimensions:
nMeshNodes = 6000 ;
nMeshFaces = 3840 ;
nFaceNodes = 4 ;
meshLayers = 20 ;
time = 1 ;
variables:
int mesh ;
mesh:cf_role = "mesh_topology" ;
mesh:long_name = "Topology data of 2D unstructured mesh." ;
mesh:topology_dimension = 2 ;
mesh:node_coordinates = "mesh_node_x mesh_node_y" ;
mesh:face_node_connectivity = "mesh_face_nodes" ;
mesh:face_dimension = "nMeshFaces" ;
uint mesh_face_nodes(nMeshFaces, nFaceNodes) ;
mesh_face_nodes:cf_role = "face_node_connectivity" ;
mesh_face_nodes:long_name = "Maps every face to its corner nodes." ;
mesh_face_nodes:_FillValue = 4294967295U ;
mesh_face_nodes:start_index = 0 ;
double mesh_node_x(nMeshNodes) ;
mesh_node_x:standard_name = "longitude" ;
mesh_node_x:long_name = "Longitude of 2D mesh nodes." ;
mesh_node_x:units = "degrees_east" ;
double mesh_node_y(nMeshNodes) ;
mesh_node_y:standard_name = "latitude" ;
mesh_node_y:long_name = "Latitude of 2D mesh nodes." ;
mesh_node_y:units = "degrees_north" ;
double mesh_depth(meshLayers, nMeshNodes) ;
mesh_depth:units = "meters" ;
mesh_depth:positive = "up" ;
mesh_depth:standard_name = "elevation" ;
mesh_depth:mesh = "mesh" ;
mesh_depth:location = "node" ;
mesh_depth:coordinates = "mesh_node_x mesh_node_y" ;
}

grid.nc.gz<https://github.com/UXARRAY/uxarray/files/8336834/grid.nc.gz>

**Comment by paullric** [comment]
A UGRID file doesn’t need to have a “Mesh2” variable.  Any variable with attribute cf_role equal to “mesh_topology” will do.

~ Paul

**Comment by rljacob** [comment]
Can we unambiguously identify the various conventions from the global attributes?  I've been concerned that's a hole in their standards.

**Comment by clyne** [comment]
> A UGRID file doesn’t need to have a “Mesh2” variable.  Any variable with attribute cf_role equal to “mesh_topology” will do.

That's my interpretation as well.

**Comment by erogluorhan** [comment]
PR #44 should have addressed this; please check
