### ISSUE TITLE
Should UGRID coordinate variables appear as xarray.coords?

### ISSUE THREAD

**Issue by clyne** [UXARRAY/uxarray#28]
Coordinate variables defined in UGRID files appear as Xarray data variables (xarray.data_vars), not coordinate variables (xarray.coords). The UGRID specification follows the CF conventions and there is sufficient information to programmatically identify the coordinate variables (as XArray does itself). Shouldn't the coordinate variables appear as xarray.coords?

To demonstrate:

load the UXarray test data set "ov_RLL10deg_CSne4.ug" and print its members:

```
uds3 = ux.open_dataset('test/meshfiles/ov_RLL10deg_CSne4.ug')
print(uds3)
```

"Mesh2_node_x" and "Mesh2_node_y" are listed as data variables even though they have 'standard_name' and 'units' attributes that identify them as coordinate variables.

**Comment by rajeeja** [comment]
Yes, they can. 
Would they be better for scaling and working with large meshes with coordinate variables?

**Comment by clyne** [comment]
I'm not sure if there would be any impact on scalability, but this would be consistent with the use of XArray elsewhere, and though I can't think of any examples at the moment, would possibly open the door to using UXarray data with XArray operators that require coordinate information.

**Comment by rajeeja** [comment]
> I'm not sure if there would be any impact on scalability, but this would be consistent with the use of XArray elsewhere, and though I can't think of any examples at the moment, would possibly open the door to using UXarray data with XArray operators that require coordinate information.

Gotcha, I can add them as coordinates.

**Comment by clyne** [comment]
Thanks!

**Comment by erogluorhan** [comment]
PR #44  should have addressed this; please check
