### ISSUE TITLE
Support for unstructured E3SM/SCREAM outputs

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#287]
https://drive.google.com/file/d/1tCkn3XK5HsOb974Vd2C_Cx17UzIfquI0

The above link contains the file:
[SCREAM.TEST.GNU.ne30pg2_ne30pg2.F2010-SCREAMv1.01.scream.h8.INSTANT.nmins_x30.0001-07-06-01800.nc](http://scream.test.gnu.ne30pg2_ne30pg2.f2010-screamv1.01.scream.h8.instant.nmins_x30.0001-07-06-01800.nc/)

There are a bunch of 2D fields written out every 30 minutes. (contains 48 time snapshot per field for the entire day)

One can start by looking at 2m temperature and see if it could be mapped onto a 1x1 degree lat/lon grid.

        float T_2m(time, ncol) ;
                T_2m:units = "K" ;
                T_2m:long_name = "T_2m" ;

Xarray output for the above grid is:

```
<xarray.Dataset>
Dimensions:               (time: 48, ncol: 21600, dim2: 2)
Coordinates:
  * time                  (time) object 0001-07-06 00:30:00 ... 0001-07-07 00...
Dimensions without coordinates: ncol, dim2
Data variables: (12/15)
    precip_liq_surf_mass  (time, ncol) float32 ...
    precip_ice_surf_mass  (time, ncol) float32 ...
    surf_evap             (time, ncol) float32 ...
    surf_sens_flux        (time, ncol) float32 ...
    ps                    (time, ncol) float32 ...
    surf_mom_flux         (time, ncol, dim2) float32 ...
    ...                    ...
    LW_flux_up@bot        (time, ncol) float32 ...
    LW_flux_dn@bot        (time, ncol) float32 ...
    surf_radiative_T      (time, ncol) float32 ...
    T_2m                  (time, ncol) float32 ...
    qv_2m                 (time, ncol) float32 ...
    wind_speed_10m        (time, ncol) float32 ...
Attributes: (12/17)
    source:           E3SM Atmosphere Model Version 4
    case:             TEST 1
    title:            EAMv4 History File
    git_hash:         THE GIT LOG HASH
    host:             THE HOST
    Version:          1.0
    ...               ...
    product:          model-output
    realm:            atmos
    Conventions:      None yet
    institution:      LLNL (Lawrence Livermore National Laboratory, Livermore...
    start_date:       10101
    start_time:       0

```

This is a possible [mesh](https://drive.google.com/file/d/1K5mILGgZrash_KcWQw3JNiI0ESBBXZ1a/edit ), will update if I find other mesh for the dataset

**Comment by gsever** [comment]
Hi Rob,
Links are available to everyone now.
Regridding works via ncremap -- following instructions from https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/754286611/Regridding+E3SM+Data+with+ncremap
Curious to see if/how Python approach works..

**Comment by rljacob** [comment]
If you're looking to try regridding, that is still off in the future for uxarray.  But we should be able to read that data with its mesh.

**Comment by gsever** [comment]
Ok, then a basic plotting example would be useful to see data in native unstructured grid.
We convert SCREAM outputs to lat/lon for ease of plotting and comparison with other gridded datasets.

**Comment by rljacob** [comment]
Gokhan, you should check out ncvis too for unstructured grids.  Its just for quick looks.  https://github.com/SEATStandards/ncvis

**Comment by gsever** [comment]
Just to note that the examples provided in these 2 links are sufficient to plot unstructured data from E3SM/SCREAM models

https://uxarray.readthedocs.io/en/latest/examples/007-polygon-viz.html

https://github.com/xCDAT/xcdat-validation/blob/main/demos/2024-e3sm-workshop/uxarray_practicum_notebook.ipynb

**Comment by erogluorhan** [comment]
We believe this is completed, so wee are closing. Please feel free to reopen if there are issues to address though
