### ISSUE TITLE
MPAS Data Read-in has duplicate `Mesh2_edge_nodes` connectivity building

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#290]
**Describe the bug**

So according to our logics, the `Grid._build_edge_node_connectivity` will build the `Mesh2_edge_nodes` and generate an `inverse_indices` for `Grid._build_face_edges_connectivity`.

And to avoid the duplicate call of  `Grid._build_edge_node_connectivity`, we have the following condition for `Grid.__init__()`:

```python
        # construct connectivity
        if "Mesh2_edge_nodes" not in self.ds:
            self._build_edge_node_connectivity()
```
However, since the mpas datafile will build a `Mesh2_edge_nodes` when reading in (`_mpas._dual_to_ugrid` and `_mpas._primal_to_ugrid` themselves will try to build the not  `Mesh2_edge_nodes` without generating the inverse_indices), it will bypass our `self._build_edge_node_connectivity()` and hence don't have the generated inverse_indices` for `Grid._build_face_edges_connectivity`.

**Solutions**
1. Force every grid object to call `self._build_edge_node_connectivity()` in the  `Grid.__init__()`
2. Or, we remove the `Mesh2_edge_nodes` attribute setup in `_mpas._dual_to_ugrid` and `_mpas._primal_to_ugrid`'
3. Change the anti-duplication condition to `        if "Mesh2_edge_nodes" not in self.ds or self.mesh_type == "mpas":
            self._build_edge_node_connectivity()`

@rajeeja @philipc2 @erogluorhan I wonder if you have any preferred solution for this? Thanks

**Comment by philipc2** [comment]
If the grid already comes with edge nodes, we shouldn't need to re-compute them. Instead, we can add a check inside of `Grid._build_edge_node_connectivity` to see whether we already have edge nodes. If we already have them, we can skip this block of code:

https://github.com/UXARRAY/uxarray/blob/e6508fd63db0dfd0c288d3f844f1f2196a5dba0b/uxarray/grid.py#L465-L477

I believe everything below that block should be able to remain the same. We would remove the following check and add it inside of `Grid._build_edge_node_connectivity()`

https://github.com/UXARRAY/uxarray/blob/e6508fd63db0dfd0c288d3f844f1f2196a5dba0b/uxarray/grid.py#L104-L105

### Proposed Change 

```Python
    def _build_edge_node_connectivity(self):
        """Constructs the UGRID connectivity variable (``Mesh2_edge_nodes``)
        and stores it within the internal (``Grid.ds``) and through the
        attribute (``Grid.Mesh2_edge_nodes``).

        Additionally, the attributes (``inverse_indices``) and
        (``fill_value_mask``) are stored for constructing other
        connectivity variables.
        """

        # need to derive edge nodes
        if "Mesh2_edge_nodes" not in self.ds: 
            padded_face_nodes = close_face_nodes(self.Mesh2_face_nodes.values,
                                                self.nMesh2_face,
                                                self.nMaxMesh2_face_nodes)

            # array of empty edge nodes where each entry is a pair of indices
            edge_nodes = np.empty((self.nMesh2_face * self.nMaxMesh2_face_nodes, 2),
                                dtype=INT_DTYPE)

            # first index includes starting node up to non-padded value
            edge_nodes[:, 0] = padded_face_nodes[:, :-1].ravel()

            # second index includes second node up to padded value
            edge_nodes[:, 1] = padded_face_nodes[:, 1:].ravel()
        else:
            edge_nodes = self.ds['Mesh2_edge_nodes'].values

        # sorted edge nodes
        edge_nodes.sort(axis=1)

        # unique edge nodes
        edge_nodes_unique, inverse_indices = np.unique(edge_nodes,
                                                       return_inverse=True,
                                                       axis=0)
        # find all edge nodes that contain a fill value
        fill_value_mask = np.logical_or(
            edge_nodes_unique[:, 0] == INT_FILL_VALUE,
            edge_nodes_unique[:, 1] == INT_FILL_VALUE)

        # all edge nodes that do not contain a fill value
        non_fill_value_mask = np.logical_not(fill_value_mask)
        edge_nodes_unique = edge_nodes_unique[non_fill_value_mask]

        # Update inverse_indices accordingly
        indices_to_update = np.where(fill_value_mask)[0]

        remove_mask = np.isin(inverse_indices, indices_to_update)
        inverse_indices[remove_mask] = INT_FILL_VALUE

        # Compute the indices where inverse_indices exceeds the values in indices_to_update
        indexes = np.searchsorted(indices_to_update,
                                  inverse_indices,
                                  side='right')
        # subtract the corresponding indexes from `inverse_indices`
        for i in range(len(inverse_indices)):
            if inverse_indices[i] != INT_FILL_VALUE:
                inverse_indices[i] -= indexes[i]


        self.ds['Mesh2_edge_nodes'] = xr.DataArray(
            edge_nodes_unique,
            dims=["nMesh2_edge", "Two"],
            attrs={
                "cf_role":
                    "edge_node_connectivity",
                "long_name":
                    "Maps every edge to the two nodes that it connects",
                "start_index":
                    INT_DTYPE(0),
                "inverse_indices":
                    inverse_indices,
                "fill_value_mask":
                    fill_value_mask
            })
            

        # set standardized attributes
        setattr(self, "Mesh2_edge_nodes", self.ds['Mesh2_edge_nodes'])
        setattr(self, "nMesh2_edge", edge_nodes_unique.shape[0])

**Comment by hongyuchen1030** [comment]
> If the grid already comes with edge nodes, we shouldn't need to re-compute them. Instead, we can add a check inside of `Grid._build_edge_node_connectivity` to see whether we already have edge nodes. If we already have them, we can skip this block of code:
> 
> https://github.com/UXARRAY/uxarray/blob/e6508fd63db0dfd0c288d3f844f1f2196a5dba0b/uxarray/grid.py#L465-L477
> 
> I believe everything below that block should be able to remain the same. We would remove the following check and add it inside of `Grid._build_edge_node_connectivity()`
> 
> https://github.com/UXARRAY/uxarray/blob/e6508fd63db0dfd0c288d3f844f1f2196a5dba0b/uxarray/grid.py#L104-L105
> 
> ### Proposed Change
> ```python
>     def _build_edge_node_connectivity(self):
>         """Constructs the UGRID connectivity variable (``Mesh2_edge_nodes``)
>         and stores it within the internal (``Grid.ds``) and through the
>         attribute (``Grid.Mesh2_edge_nodes``).
> 
>         Additionally, the attributes (``inverse_indices``) and
>         (``fill_value_mask``) are stored for constructing other
>         connectivity variables.
>         """
> 
>         # need to derive edge nodes
>         if "Mesh2_edge_nodes" not in self.ds: 
>             padded_face_nodes = close_face_nodes(self.Mesh2_face_nodes.values,
>                                                 self.nMesh2_face,
>                                                 self.nMaxMesh2_face_nodes)
> 
>             # array of empty edge nodes where each entry is a pair of indices
>             edge_nodes = np.empty((self.nMesh2_face * self.nMaxMesh2_face_nodes, 2),
>                                 dtype=INT_DTYPE)
> 
>             # first index includes starting node up to non-padded value
>             edge_nodes[:, 0] = padded_face_nodes[:, :-1].ravel()
> 
>             # second index includes second node up to padded value
>             edge_nodes[:, 1] = padded_face_nodes[:, 1:].ravel()
>         else:
>             edge_nodes = self.ds['Mesh2_edge_nodes'].values
> 
>         # sorted edge nodes
>         edge_nodes.sort(axis=1)
> 
>         # unique edge nodes
>         edge_nodes_unique, inverse_indices = np.unique(edge_nodes,
>                                                        return_inverse=True,
>                                                        axis=0)
>         # find all edge nodes that contain a fill value
>         fill_value_mask = np.logical_or(
>             edge_nodes_unique[:, 0] == INT_FILL_VALUE,
>             edge_nodes_unique[:, 1] == INT_FILL_VALUE)
> 
>         # all edge nodes that do not contain a fill value
>         non_fill_value_mask = np.logical_not(fill_value_mask)
>         edge_nodes_unique = edge_nodes_unique[non_fill_value_mask]
> 
>         # Update inverse_indices accordingly
>         indices_to_update = np.where(fill_value_mask)[0]
> 
>         remove_mask = np.isin(inverse_indices, indices_to_update)
>         inverse_indices[remove_mask] = INT_FILL_VALUE
> 
>         # Compute the indices where inverse_indices exceeds the values in indices_to_update
>         indexes = np.searchsorted(indices_to_update,
>                                   inverse_indices,
>                                   side='right')
>         # subtract the corresponding indexes from `inverse_indices`
>         for i in range(len(inverse_indices)):
>             if inverse_indices[i] != INT_FILL_VALUE:
>                 inverse_indices[i] -= indexes[i]
> 
> 
>         self.ds['Mesh2_edge_nodes'] = xr.DataArray(
>             edge_nodes_unique,
>             dims=["nMesh2_edge", "Two"],
>             attrs={
>                 "cf_role":
>                     "edge_node_connectivity",
>                 "long_name":
>                     "Maps every edge to the two nodes that it connects",
>                 "start_index":
>                     INT_DTYPE(0),
>                 "inverse_indices":
>                     inverse_indices,
>                 "fill_value_mask":
>                     fill_value_mask
>             })
>             
> 
>         # set standardized attributes
>         setattr(self, "Mesh2_edge_nodes", self.ds['Mesh2_edge_nodes'])
>         setattr(self, "nMesh2_edge", edge_nodes_unique.shape[0])
> ```

Thanks for your information 

However, when I tried testing it by using the `mpas` dataset, it shows that when passing into
the `Grid._build_edge_node_connectivity`, it has `self.ds['Mesh2_edge_nodes'] ` as a 480 * 2 array and `self.ds['Mesh2_face_nodes'] ` as a 162 * 6 array. 

Indicating that the original reading `edge_nodes` from the `mpas` dataset is already unique edges. This means we'll lose the information for the `inverse_indices` unless we rebuild it from `face_nodes_connectivity`

**Comment by hongyuchen1030** [comment]
This also indicates that the Testcase `TestConnectivity.test_build_edge_nodes()` didn't actually test the construction of (`Mesh2_edge_nodes`) on an MPAS grid, it only test the data read-in for the MPAS. In fact, this test case uses highly similar logic to the `_build_edge_node_connectivity()`, that's also probably why it could pass
