### ISSUE TITLE
Coordinates are not stored as `ux.UxDataArray`

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#301]
If a dataset contains data variables with defined coordinates, they are internally stored as a `xr.DataArray` and not `ux.UxDataArray`, which causes them to not have a `uxgrid` accessor

**Comment by erogluorhan** [comment]
Should we have the coordinates stored as UxDataArray, or have uxgrid accessor?

**Comment by rajeeja** [comment]
uxgrid accessor is fine as it encapsulates it well. I hope we don't lose on any advantage that xarray coords has due to this.

What other major reasons do you think for this change?
