### ISSUE TITLE
Allow `face_nodes_connectivity` combined with `node_coordinates` as input for `Grid.__from_vert__()`

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#304]
**Describe the feature you'd like added to this project**
I would like to add the ability for users to initialize a Grid object using both `face_nodes_connectivity` and `node_coordinates` as input parameters for the `Grid.__from_vert__()` method.

**Describe the solution you'd like**
The solution would be to accept two input arrays: `node_latlon_degree` and `face_nodes_conn_index`. These arrays would be used to initialize the Grid object and would contain both the node coordinates and the connectivity information for each face. 

Here is an example of what the input arrays would look like:
```python
node_latlon_degree = [[162., 30], [216., 30], [70., 30], [162., -30], [216., -30], [70., -30]]
face_nodes_conn_index = np.array([[3, 4, 5, ux.INT_FILL_VALUE], [3, 0, 2, 5], [3, 4, 1, 0], [0, 1, 2, ux.INT_FILL_VALUE]])
```

Internally, these two arrays would be combined into a `n_face x m_nodes_per_face` array that includes the connectivity information with node coordinates like the following
```python
conn_coordinates = [
    [
        [162, -30],
        [216, -30],
        [70, -30],
        [ux.INT_FILL_VALUE, ux.INT_FILL_VALUE]
    ],
    [
        [162, -30],
        [162, 30],
        [70, 30],
        [70, -30]
    ],
    [
        [162, -30],
        [216, -30],
        [216, 30],
        [162, 30]
    ],
    [
        [162, 30],
        [216, 30],
        [70, 30],
        [ux.INT_FILL_VALUE, ux.INT_FILL_VALUE]
    ]
]


```

**Additional context**
This enhancement would give users more flexibility when initializing Grid objects and make it easier to work with node coordinates and face connectivity information.

**Comment by philipc2** [comment]
I believe the issue lies here within your most recent PR #297 

https://github.com/UXARRAY/uxarray/blob/5e8aebe4f68d8186a8019412c43c0181f09f6409/uxarray/grid.py#L486-L488

If we have already parsed our input dataset and stored `Mesh2_edge_nodes` within our `Grid`, we still want to ensure that they are sorted and unique (lines below). This also makes it so that we will have our `inverse_indices` and `inverse_mask` computed.

The following test (same one that was remove in #297) operates as expected with the following change.

```Python
if "Mesh2_edge_nodes" not in self.ds or repopulate:
     # same body as before, unchanged
else:
    edge_nodes = self.ds["Mesh2_edge_nodes"].values
```

This is the slightly modified test case to use the `repopulate` parameter

```Python
    def test_build_edge_nodes_connectivity(self):
        """ Give a set of known (``Mesh2_edge_nodes``) from an MPAS dataset,
        compare result computed in (``Grid._build_edge_node_connectivity``) in
        order to ensure both sorted unique, sorted versions are equivalent
        """

        mpas_grid_xr = xr.open_dataset(self.mpas_filepath)
        mpas_grid_ux = ux.Grid(mpas_grid_xr)

        # unique, sorted version of MPAS edge nodes
        edge_nodes_expected = mpas_grid_ux.ds['Mesh2_edge_nodes'].values

        # computed edges nodes derived from padded face nodes
        mpas_grid_ux._build_edge_node_connectivity(repopulate=True)
        edge_nodes_output = mpas_grid_ux.ds['Mesh2_edge_nodes'].values

        nt.assert_array_equal(edge_nodes_expected, edge_nodes_output)
```


Shouldn't this also eliminate the need to call `Grid._build_edge_node_connectivity(repopulate=True)` from within `Grid._build_face_edge_connectivity` because our edge nodes will always have the expected attributes.

**Comment by hongyuchen1030** [comment]
> I believe the issue lies here within your most recent PR #297
> 
> https://github.com/UXARRAY/uxarray/blob/5e8aebe4f68d8186a8019412c43c0181f09f6409/uxarray/grid.py#L486-L488
> 
> If we have already parsed our input dataset and stored `Mesh2_edge_nodes` within our `Grid`, we still want to ensure that they are sorted and unique (lines below). This also makes it so that we will have our `inverse_indices` and `inverse_mask` computed.
> 
> The following test (same one that was remove in #297) operates as expected with the following change.
> 
> ```python
> if "Mesh2_edge_nodes" not in self.ds or repopulate:
>      # same body as before, unchanged
> else:
>     edge_nodes = self.ds["Mesh2_edge_nodes"].values
> ```
> 
> This is the slightly modified test case to use the `repopulate` parameter
> 
> ```python
>     def test_build_edge_nodes_connectivity(self):
>         """ Give a set of known (``Mesh2_edge_nodes``) from an MPAS dataset,
>         compare result computed in (``Grid._build_edge_node_connectivity``) 
>         to ensure both sorted unique, sorted versions are equivalent
>         """
> 
>         mpas_grid_xr = xr.open_dataset(self.mpas_filepath)
>         mpas_grid_ux = ux.Grid(mpas_grid_xr)
> 
>         # unique, sorted version of MPAS edge nodes
>         edge_nodes_expected = mpas_grid_ux.ds['Mesh2_edge_nodes'].values
> 
>         # computed edges nodes derived from padded face nodes
>         mpas_grid_ux._build_edge_node_connectivity(repopulate=True)
>         edge_nodes_output = mpas_grid_ux.ds['Mesh2_edge_nodes'].values
> 
>         nt.assert_array_equal(edge_nodes_expected, edge_nodes_output)
> ```
> 
> Shouldn't this also eliminate the need to call `Grid._build_edge_node_connectivity(repopulate=True)` from within `Grid._build_face_edge_connectivity` because our edge nodes will always have the expected attributes.

Before proceeding. First, this issue has nothing to do with the `Grid.face_nodes_connectivity`. This issue is only for the `Grid.__from_vert__` and I think my examples attached above also explain this situation clearly.

**Comment by hongyuchen1030** [comment]
I will move your comment to the PR and continue the discussion over there

**Comment by philipc2** [comment]
> I will move your comment to the PR and continue the discussion over there

Thank you, I thought I was typing it somewhere else at first.
