### ISSUE TITLE
Release v2023.05.0

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#309]

**Comment by anissa111** [comment]
Updating to say that the May release will be made tomorrow, with a dev release of the redesign prototype and a regular release on the main branch.

**Comment by anissa111** [comment]
Still waiting on the v2023.05.0 version bump, but the dev release on the prototype redesign is live on pypi and not showing up as the latest version as expected. I will update this issue further when the dev release is live on conda-forge as well

![image](https://github.com/UXARRAY/uxarray/assets/38434768/ff94ccf9-09a5-4760-9e74-bd9dd5edf43f)

**Comment by anissa111** [comment]
Alright! Regular and dev releases are live on conda-forge and pypi.

To install the dev release from pypi:
```bash
pip install uxarray==2023.5.0.dev0
```

To install the dev release from conda-forge:
```bash
conda install -c "conda-forge/label/uxarray_dev" uxarray
```

The dev release won't install by default on either platform and will only install if specified like above.
