### ISSUE TITLE
Global Constant for Default Error Bounds

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#312]
**Describe the feature you'd like added to this project**
We require a universal constant to account for error tolerance in our project. Users will be able to define this constant, but if they do not specify a value, a default value of approximately 1.0e-15 will be used.

**Additional context**
This feature would be useful for ensuring consistency and accuracy in our project. It would also make it easier for users to customize their experience.

**Comment by philipc2** [comment]
This has already been implemented, presumably as part of some of the other functionality you implemented.

https://github.com/UXARRAY/uxarray/blob/682127e6cb6f53675ec012702c640d159583e17a/uxarray/constants.py#L13
