### ISSUE TITLE
Grid Topology Representation between Dataset, DataArray, and Grid 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#324]
We are storing all grid variables through an internal dataset (`uxgrid._ds`) and access attributes (`uxgrid.Mesh2_node_x`) under our `uxgrid` accessor.

This works fine for the `Grid` class, however access to this dataset is not clear for the Dataset and DataArray classes. We would like a better way to access our grid variables. 

One solution would be the following:
* Keep the internal `_ds` and access attributes the same
* Implement a `uxds.topology` or `uxda.topology` access attribute which would act like `uxds.coords` or `uxds.dims`, but would return our `ugrid._ds`. This would allow us to keep the `uxgrid._ds` as an internal grid representation in our Grid and provide a way to access these varibles outside of the Grid class. 

This would be similar to what `xarray` does:
```Python
    @property
    def coords(self) -> DataArrayCoordinates:
        """Dictionary-like container of coordinate arrays."""
        return DataArrayCoordinates(self)
```

**Comment by erogluorhan** [comment]
A few thoughts:

In this new design with UxDataset and UxDataArray, the `Grid` object itself is their property, i.e. `uxgrid`, for the sake of providing grid topology information through dataset and array. That said: 

- Introducing a new property `.topology` look redundant with the existence of `uxgrid`.  
   - So, instead of having `.uxgrid` and `.topology` properties simultaneously (especially with the proposal that topology just returning the protected `_ds`, i.e. see below comment), we may want to have:
      - `uxgrid` property providing some user API to satisfy this topology info need or implement uxgrid in way that it'd behave as if it was a dictionary like entity, e.g. `uxds.uxgrid["Mesh2_..."]`
      - UxDataset and  UxDataArray providing user APIs, if needed, for specific attributes 
- The motivation behind making `_ds`protected is because it may have non-standardized attribute names etc. but `uxgrid` should have all of them in a standardized UGRID way. 
   - So, instead of returning `_ds` directly, we may want to have a user API to provide only the attributes we want the user to access, e.g. those with standardized names etc.

**Comment by erogluorhan** [comment]
> This type of implementation would take some time, which is why I chose to go with a simple fix with simply returning the internal grid dataset (`_ds`) right now as a placeholder for this type of implementation. 

Even though this makes sense, providing a placeholder in the user API without much design-thought, may not be the best option as we may end up with a significantly different decision (especially as we are close to deploy this new design). Instead, `grid._ds` with its cons would work in the meantime, and we can have the actual opportunity to think about what an user API should be here. 

I am also curious about @dcherian 's thoughts though.

**Comment by dcherian** [comment]
>  do we want to implement this functionality directly within our Grid, or would we still want to create a separate Topology class that would act like the Coordinates one above? 

Why do you need a separate class? You could return a dataset or `_ds.coords` and keep it simpler.

**Comment by philipc2** [comment]
> Why do you need a separate class?

I was considering a design where our `UxDataset` and `UxDataArray` would have a way to access all grid topology variables in a format that is similar to doing `ds.coords`. `ds.coords` only stores variables such as `Mesh2_node_x`, `Mesh2_node_y`, mesh layers, time, etc. We would like to store connectivity variables in a similar way, through something like `ds.topology`. However, as @erogluorhan metioned, having both a `ds.uxgrid` and `ds.topology` could lead to some confusion. 

One alternative would be that we extend `ds.uxgrid` to allow for dictionary like indexing to obtain grid variables (`ds.uxgrid['Mesh2_face_nodes']`).

> You could return a dataset or _ds.coords and keep it simpler

Using a dataset would work, and it is essentially what we are currently doing. However, my vision for the design would be to have the topology stored like coordinates so that we could represent a dataset or data array in terms of: Dimensions, Coordinates, **Topology**, Data Variables, Indexes, & Attributes (we'd include a topology drop down section below). This is related to #237

![image](https://github.com/UXARRAY/uxarray/assets/67855069/0d2f1e88-82a6-4961-8b25-8c33b2be86f1)

**Comment by dcherian** [comment]
> topology stored like coordinates 

SO Xarray does not "store" coordinates separately. There is `Dataset._variables` which is a ="bag of variables" and `Dataset._coord_names` which is a list of variable names that are coordianates. The "Coordinates" objects are constructed when the user requests them, and are usually used just for user-facing API (This may be changing now).

In any case for your purposes it seems like all you need are a list of topology variables and a property that will return those variables as a dataset when the user requests it.

**Comment by hongyuchen1030** [comment]
> > Why do you need a separate class?
> 
> I was considering a design where our `UxDataset` and `UxDataArray` would have a way to access all grid topology variables in a format that is similar to doing `ds.coords`. `ds.coords` only stores variables such as `Mesh2_node_x`, `Mesh2_node_y`, mesh layers, time, etc. We would like to store connectivity variables in a similar way, through something like `ds.topology`. However, as @erogluorhan metioned, having both a `ds.uxgrid` and `ds.topology` could lead to some confusion.
> 
> One alternative would be that we extend `ds.uxgrid` to allow for dictionary like indexing to obtain grid variables (`ds.uxgrid['Mesh2_face_nodes']`).
> 
> > You could return a dataset or _ds.coords and keep it simpler
> 
> Using a dataset would work, and it is essentially what we are currently doing. However, my vision for the design would be to have the topology stored like coordinates so that we could represent a dataset or data array in terms of: Dimensions, Coordinates, **Topology**, Data Variables, Indexes, & Attributes (we'd include a topology drop down section below). This is related to #237
> 
> ![image](https://user-images.githubusercontent.com/67855069/242945738-0d2f1e88-82a6-4961-8b25-8c33b2be86f1.png)

I agree that we shouldn't keep adding different `class` or baggy APIs for the topology. And After reading all conversation, I feel like this dictionary one make more sense to me.

> One alternative would be that we extend ds.uxgrid to allow for dictionary like indexing to obtain grid variables (ds.uxgrid['Mesh2_face_nodes']).

**Comment by philipc2** [comment]
@hongyuchen1030 

I have actually just pushed some recent changes to #325 that should address these concerns.
