### ISSUE TITLE
[Release]: v2023.06.0

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#335]
Date of intended release: June 8th, 2023

## Release progress checklist

- [x] CI tests are passing
- [x] update version number in `meta.yaml`
- [x] a new tag and release has been made on GitHub
- [x] feedstock PR has been merged
- [x] release on pypi action has been triggered and run successfully
- [x] new version can be installed via pip
- [x] new version can be installed via conda

**Comment by anissa111** [comment]
Just an update, I'm aiming to have this completed/verified by EOD tomorrow now that the redesign has been merged
