### ISSUE TITLE
Functions for Constructing `Mesh2_face_x` & `Mesh2_face_y`

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#340]
Create functions for constructing the UGRID coordinate variables `Mesh2_face_x` and `Mesh2_face_y`, which represent the center longitude and latitude of each face respectively. 

`_build_face_coordinates` or equivalent

**Comment by philipc2** [comment]
@aaronzedwick 

Can you revisit this, however instead of using the lat/lon coordinates to calculate the average, can you see how using Cartesian coordinates works?

**Comment by aaronzedwick** [comment]
> @aaronzedwick
> 
> Can you revisit this, however instead of using the lat/lon coordinates to calculate the average, can you see how using Cartesian coordinates works?

Sure! That is a good idea
