### ISSUE TITLE
Development Roadmap Section in Documentation

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#348]
As opposed to having our development roadmap split between discussion posts, internal meeting documents, and the draft API, we could collect all of these into a section under our documentation, similar to what is being done with [Xarray](https://docs.xarray.dev/en/stable/roadmap.html).

**Comment by hongyuchen1030** [comment]
I think this discussion page might be helpful https://github.com/UXARRAY/uxarray/discussions/358

**Comment by erogluorhan** [comment]
Milestones interface working well for this purpose for now as we have only one significant repo.

**Comment by philipc2** [comment]
Closing this as our [Milestones ](https://github.com/UXARRAY/uxarray/milestones) are used for this purpose.
