### ISSUE TITLE
Minimal Create From Vertex

### ISSUE THREAD

**Issue by anissa111** [UXARRAY/uxarray#35]
# Minimal Create From Vertex
As a way to start us off, I'll get us started with a quirk I found. The API allows for the creation of a `ux.Grid()` from vertices. Presumably this would require at least three vertices.

If you try to initialize with one point, an error is returned as expected. This
```python3
import uxarry as ux
import numpy as np

# initialize with one point
line = np.array([[0, 0]])
ux_line = ux.Grid(line)
```
will return `ValueError: different number of dimensions on data and dims: 0 vs 1`

However, if you try to initialize with two points, no error is given:
```python3
# initialize with two points
line = np.array([[0, 0], [1, 1]])
ux_line = ux.Grid(line)
```

Should we throw an error for this input and maybe provide a custom error for initialization with one point? Should we also check that the vertices provided are unique?

Let's talk about it!

_Originally posted by @anissa111 in https://github.com/UXARRAY/uxarray/discussions/34#discussioncomment-2562494_

**Comment by rajeeja** [comment]
Good issue. The idea of "create from vertex" is for testing purposes only (I think).
Do vertices follow spherical/cartesian system? - some changes in the `integration` branch regarding this has been added, it'd be good to formalize the requirements.
If we allow both, we can convert to cartesian (internally) and we might also enforce or make them `verticies_unit_magnitude`?
