### ISSUE TITLE
Cartesian Coordinates Improperly Labeled as Lat/Lon for Exodus Grids

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#360]
## Overview
Cartesian Coordinates parsed from Exodus grids that are incorrectly labeled with units "degrees", meaning they are interpreted as lat/lon.

## MCVE

Dataset Used: Exodus outCSne8

```Python
# Base data path
base_path = "../../test/meshfiles/exodus/outCSne8/"

# Path to Grid file
grid_path = base_path + "outCSne8.g"

uxgrid = ux.open_grid(grid_path)
```

```Python
uxgrid.Mesh2_node_x.units
```
<img width="137" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/8a9c51bc-14e1-43bc-8876-a6931899fdc6">

```Python
uxgrid.Mesh2_node_x.values.min(), uxgrid.Mesh2_node_x.values.max()
```

<img width="142" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/154f0d31-c231-4cce-9c9d-cb606d1c938e">

**Comment by rajeeja** [comment]
will fix.

**Comment by brianpm** [comment]
I just ran into this same issue "in the wild" yesterday when I tried to use an exodus file.

**Comment by rajeeja** [comment]
Is the assumption that exodus II meshes are always cartesian (defined in the basic
cartesian coordinate system) valid? 

Anyone has example of a lat/lon coord exodus mesh file? 

I tried to look for some symbol in the netcdf loaded from xarray and didn't find anything specific. Documentation talks about frames with "S": spherical, "R": cartesian and "C": cylinderical see [docs pg. 112](https://ftp.mcs.anl.gov/pub/pdetools/nightlylogs/xsdk/xsdk-configuration-tester/packages/trilinos/packages/seacas/doc/exodusII-new.pdf)
