### ISSUE TITLE
Shouldn't `open_dataset` return Grid object? 

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#39]
Our `open_dataset` function currently returns `Grid.ds` (See [here](https://github.com/UXARRAY/uxarray/blob/328b4448fbf4bb289882ed15d800be4c0cf12cd0/uxarray/dataset.py#L48) ), which is of type `xarray.Dataset`, but I think we should return Grid object itself. Any thoughts?

**Comment by michaelavs** [comment]
Was this addressed with PR #41 yesterday? I see it referenced in here, but want to double check before closing out this issue

**Comment by rajeeja** [comment]
Yes. Merged to main
