### ISSUE TITLE
Nearest Neighbor Regridding

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#397]
**Describe the feature you'd like added to this project**

KDTree needs to be built on the source mesh, then sampled on the target 

**Describe the solution you'd like**

load two meshes a and b into uxarray
map a variable say temperature from mesh a onto mesh b.

Note: this functionality will need a function that takes two meshes as arguments! 

**Additional context**
use `scipy.spatial`

**Comment by philipc2** [comment]
@rajeeja 

Splitting this issue up with #404
