### ISSUE TITLE
Regarding Grid.filename

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#40]
Our Uxarray API has a `Grid.filename` attribute for Grid that is initiated through files. There are two things to review about it as follows:

1. It is currently implemented to keep track of the full file path (not only file name), see [here](https://github.com/UXARRAY/uxarray/blob/328b4448fbf4bb289882ed15d800be4c0cf12cd0/uxarray/grid.py#L90). Should it be file name or file path; pros/cons with either? 
2. Shouldn't we also keep track of file names/paths when opening multiple dataset files through `open_dataset`. We currently implement this to initiate the `Grid` object using the Grid definition file (so, keeping track of its file path), then other dataset files are just merged to `Grid.ds` [here](https://github.com/UXARRAY/uxarray/blob/328b4448fbf4bb289882ed15d800be4c0cf12cd0/uxarray/dataset.py#L45). My proposal for this line of code could be  something like:

`ux_grid.add_dataset(all_data, args)`

Then, we could define a `add_dataset` function as a helper function for grid.py as something like:

```
def add_dataset(ds_to_add, filename):
     self.ds = xr.merge([self.ds, ds_to_add]) 
     self.filepath = self.filepath + ', ' + filename
```

Or, a different way to keep multiple strings for filename/filepath.

**Comment by rajeeja** [comment]
What is the use case of keeping track of filename or paths?
Once loaded, we're done. No need to keep track or am I missing something?

We might need the "path" for only when saving a file; that also we can assume that we'll save in the original path supplied by the user.

**Comment by erogluorhan** [comment]
Good question, @rajeeja ! I don't have an immediate answer. Any thoughts? @brianpm @zarzycki @clyne @paullric @rljacob

**Comment by clyne** [comment]
If there are multiple files involved in constructing a single data set, maintaining the path names would be helpful for error reporting to the user.

**Comment by brianpm** [comment]
No strong opinion about this. I think the full file name or list of files would be my slight preference. My only use case would be along the lines that John said. If something looks wrong, check that the expected files were used... if still suspicious, go investigate the files directly.

**Comment by zarzycki** [comment]
I'll just note I agree with the above. Not a fan of the potential of leveraging the file path to save any new file in said path (I could envision unexpected behavior there)
... however for diagnostics (either straight up error trap by code itself or valid, but odd, behavior the user must investigate) it seems prudent to be able to pass information about the full path/filename back.

**Comment by paullric** [comment]
Agree with Colin.  There is value in retaining the filename/path, but it should purely be for diagnostics and reporting.

~ Paul

**Comment by erogluorhan** [comment]
Great input, thanks everyone! It seems like we have a consensus to keep track of file paths, but only for diagnostics and reporting.
