### ISSUE TITLE
Missing a lot of user API functions in the namespace

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#416]
**Describe the bug**
I think we haven't included several user API functions/properties (e.g. `grid.coordinates.node_lonlat_rad_to_xyz`) in the namespace after the recent code refactoring (i.e. "grid" dir creation and several helper scripts addition) even though we list them under `docs/user_api/index.rst`

**To Reproduce**
1. In any IDE, check if you can access such functions through the `grid` object.

**Expected behavior**
We should be importing them in the code so that they could show up in the namespace.

cc @philipc2

**Comment by philipc2** [comment]
> In any IDE, check if you can access such functions through the grid object.

This is expected behavior with these functions, since they are not tied to the `Grid` object. We should consider making them internal if everything under `uxarray/grid` should be directly tied to a `Grid` object. 

This also raises an important question:
- Should we ever consider creating a user-facing API function that isn't directly tied to one of our data structures (`Grid`, `UxDataArray`, `UxDataset`), essentially removing any user-facing "helper" functions. 

I'm in favor of having all of our functionality directly tied to our core data structures.

**Comment by erogluorhan** [comment]
> I'm in favor of having all of our functionality directly tied to our core data structures.

Did you mean "whatever functions in the user API should ONLY be tied to one of our core data structures" instead of "ALL the functionality"? If so, I agree with that for majority of our functions. There are and will be some functions (e.g. `open_dataset`) that are directly callable from the `uxarray.` level though (Xarray has a similar behavior, too). 

> This is expected behavior with these functions, since they are not tied to the Grid object. We should consider making them internal if everything under uxarray/grid should be directly tied to a Grid object.

Well, I think it will depend on how we interpret them. 

They are listed in the user API docs as follows, for instance:

```
Helpers
======
Coordinates
------------
grid.coordinates.node_lonlat_rad_to_xyz
```

- This might be understood as that even though this function is not directly tied to `Grid`, it can still be in the user API if the user explicitly imports it as follows (or alternatively call it through the following same namespace:

`from uxarray.grid.coordinates import node_lonlat_rad_to_xyz`

Is it how you assume such functions' usage in the user API as well?

- We can still consider getting some of these functions tied to our data structures if we think they are potentially frequently usable that way (I don't know if we have had any of such functions tied already, but for example, PR #299 attempts to tie `normalize_in_place` to `grid`; see [here](https://github.com/UXARRAY/uxarray/pull/299/files#:~:text=from%20uxarray.grid.coordinates%20import%20(normalize_in_place%2C))
