### ISSUE TITLE
Timing and Memory Benchmarking using Airspeed Velocity (ASV)

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#420]
Airspeed Velocity is a tool for benchmarking Python packages, including runtime, memory usage, and custom metrics. Results are displayed using [integrative pages](https://pv.github.io/numpy-bench/). 

###### See [Numpy ](https://github.com/numpy/numpy/tree/main/benchmarks)and [SciPy ](https://github.com/scipy/scipy/tree/main/benchmarks)for examples

**Comment by philipc2** [comment]
@rajeeja 

We are currently working on getting `asv` set up with `geocat-comp`. Once we have a baseline set up there, we can port it over here.

**Comment by rajeeja** [comment]
Has anyone tried _scalene_? https://techxplore.com/news/2023-08-scientists-open-source-tool-language-python.html
