### ISSUE TITLE
Inverse Distance Weighted Remapping

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#443]
Implement Inverse Distance Weighted (IDW) Remapping, with options to select how many nearest neighbors (k) to use for the weighting. 

A good read into the underlying algorithm [here](https://help.rockware.com/rockworks17/WebHelp/gridding_inv_dist.htm#:~:text=Inverse%2DDistance%20is%20one%20of,number%20of%20directionally%20distributed%20neighbors.)

**Comment by philipc2** [comment]
@aaronzedwick 

Issue should be updated now! I'll also ping @paullric since we discussed this a while back ago if he has any pointers or comments to add.

**Comment by aaronzedwick** [comment]
> @aaronzedwick
> 
> Issue should be updated now! I'll also ping @paullric since we discussed this a while back ago if he has any pointers or comments to add.

Thanks!
