### ISSUE TITLE
`uxarray.Grid.Mesh2_node_x` vs UGRID's flexible naming 

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#45]
We are currently implementing the flexible variable naming in UGRID conventions through dynamic variable naming in xArray.Dataset, i.e. `Uxarray.Grid.ds`, with the help of a dictionary (See PR #44).

However, we are proposing to have [uxarray.Grid.Mesh2_node_x](https://github.com/UXARRAY/uxarray/blob/main/docs/user_api/uxarray_api.md#:~:text=uxarray.Grid.Mesh2_node_x%3A%20np.float64%20DataArray%20of%20size%20(nMesh2_node)) et al., i.e. standard name variables, in our API, too.

To comply with our API as well as to provide the user with a standardized naming set in addition to keeping track of original dataset names in our `Uxarray.Grid.ds`, should we provide `Uxarray.Grid.mesh2_node_x` et al. functions that would simple access `Uxarray.Grid.ds.<actual variable name>`?

For instance, if we had `my_ugrid_node_x` variable coming from a netCDF file, one would be able to access this through two ways like:

`Uxarray.Grid.ds.my_ugrid_node_x`
`Uxarray.Grid.mesh2_node_x` 

Any concerns such as it'd lead to confusions?

@anissa111 @michaelavs  @paullric @rajeeja @rljacob

**Comment by rajeeja** [comment]
Maybe, we can do this as a part 2 of this fix.

**Comment by erogluorhan** [comment]
I share your concerns @rajeeja

**Comment by erogluorhan** [comment]
> From experience with [cf_xarray](https://cf-xarray.readthedocs.io/en/latest/), I think that having a way to access using "standard names" Grid.XXX and a way to use model-specific names through Grid.ds.YYY is very useful.

> It makes it easier to slowly switch code from model-specific names to using the "standard name" that will generalize to multiple models.

Great point, thanks!
