### ISSUE TITLE
Possibles tweaks to 005 usage example

### ISSUE THREAD

**Issue by zarzycki** [UXARRAY/uxarray#461]
A couple things I ran into reproducing the [005 usage example](https://uxarray.readthedocs.io/en/stable/examples/005-to-geodataframe-for-holoviz.html)... not sure if these classify as "bugs"

Remove commas here -- isn't the standard way in conda/mamba to just have spaces?

```
conda install -c pyviz holoviews, hvplot, geoviews
```

On this cell:

```
gdf_grid = uxds.uxgrid.to_geodataframe()
gdf_grid
```

I had to install...

```
mamba install -c conda-forge spatialpandas antimeridian
``` 

since neither came with my env install of:

```
mamba create -n uxarray -c conda-forge uxarray holoviews hvplot geoviews
```

**Comment by philipc2** [comment]
@zarzycki 

Thanks for pointing these out!

**Comment by erogluorhan** [comment]
Hey @zarzycki thanks a lot for the feedback; it should be fixed now!
