### ISSUE TITLE
MPAS lack of optional connectivity vars leads to exception

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#469]
**Describe the bug**
There are some connectivity variables such as `verticesOnEdge`, lack of which shouldn't prevent UXarray from constructing the grid. 

**To Reproduce**
1. Try opening 3.75km DYAMOND grid, courtesy of @falkojudt 
2. See the exception (i.e. grid type not correct) due to lack of `verticesOnEdge`
3. You can also observe meshes from the other resolutions (7.5km, 15km, 30km) have this variable, so they can be opened with UXarray.

**Expected behavior**
UXarray.Grid should still be constructed  with lack of `verticesOnEdge` or similar vars.

**Comment by philipc2** [comment]
This has been resolved.
