### ISSUE TITLE
Face Edge Connectivity in Cartesian Coordinates

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#515]
**Describe the feature you'd like added to this project**
This feature aims to build a `face_edge_cart` representation: an ndarray that describes a face polygon through its edges in Cartesian coordinates. The representation is shaped as `(n_edges, 2, 3)`.

Which acts as a preprocess step for #510 

### **Link to original functionality implementation elsewhere, if applicable:**
N/A

### **Links to other examples, if applicable:**
N/A

### **Describe the solution you'd like:**
Utilizing the Grid attributes `Grid.Mesh2_edge_nodes` and `Grid.Mesh2_face_edges`, the solution seeks to map every edge to the two nodes it connects and subsequently map every face to its edges. The dimensionality and data type details for these attributes are:
- `Grid.Mesh2_edge_nodes`: Dimensions `(nMesh2_edge, Two)`, DataType `INT_DTYPE`. This maps every edge to the two nodes it connects, with nodes in arbitrary order.
- `Grid.Mesh2_face_edges`: Dimensions `(nMesh2_face, nMaxMesh2_face_nodes)`, DataType `INT_DTYPE`. This maps every face to its associated edges.
- `Mesh2_face_cart_x/y/z`: These are coordinate attributes containing the Cartesian x, y, and z locations of each face center in meters.

The solution involves combining the connectivity from the above attributes with the Cartesian coordinates to build the desired `face_edge_cart` ndarray representation.

**Comment by philipc2** [comment]
I would be careful with how we chose to implement this. `Mesh2_face_edges` is our connectivity variable, and creating a `Mesh2_face_edges_cart` would no longer be connectivity (it would simply be our cartesiain x/y/z used to index our Cartesian coordinates.

In an iteration or two, we are planning to deprecate the `Mesh2` prefix and clean up our dimension, coordinate, and connectivity names to be more clear & pythonic.

When we make this change, this is how I see this being implemented

#### `Mesh2_face_edges` $\implies$ `face_edge_connectivity`

#### `face_edge_cart` $\implies$ `face_edges_xyz` (or similar) 


For now, maybe a `Grid` helper function that is defined as follows:

```Python
def get_face_edges(self, coord_type: Optional[str] = "latlon"):
    if coord_type == "latlon":
        # index lat/lon coords and return face edges
    elif: coord_type = "cartesian":
        # index x/y/z coords and return face edges
```

Having similar functions for face nodes and all other connectivities would be really usefull!

**Comment by hongyuchen1030** [comment]
> I would be careful with how we chose to implement this. `Mesh2_face_edges` is our connectivity variable, and creating a `Mesh2_face_edges_cart` would no longer be connectivity (it would simply be our cartesiain x/y/z used to index our Cartesian coordinates.
> 
> In an iteration or two, we are planning to deprecate the `Mesh2` prefix and clean up our dimension, coordinate, and connectivity names to be more clear & pythonic.
> 
> When we make this change, this is how I see this being implemented
> 
> #### `Mesh2_face_edges` 
> ⟹
>  `face_edge_connectivity`
> #### `face_edge_cart` 
> ⟹
>  `face_edges_xyz` (or similar)
> For now, maybe a `Grid` helper function that is defined as follows would get the job done without needing to create any new public attributes.
> 
> ```python
> def get_face_edges(self, coord_type: Optional[str] = "latlon"):
>     if coord_type == "latlon":
>         # index lat/lon coords and return face edges
>     elif: coord_type = "cartesian":
>         # index x/y/z coords and return face edges
> ```
> 
> Having similar functions for face nodes and all other connectivities would be really useful!

Thank you for you advice. However, I never plan to put this into our `Grid` attribute, this will just serve as a little helper function to conveniently preprocess the data for my following geometry functionalities. That's also why I didn't use `Grid.face_edge_carts` as my title but instead just `face_edg_carts`

**Comment by philipc2** [comment]
> > I would be careful with how we chose to implement this. `Mesh2_face_edges` is our connectivity variable, and creating a `Mesh2_face_edges_cart` would no longer be connectivity (it would simply be our cartesiain x/y/z used to index our Cartesian coordinates.
> > In an iteration or two, we are planning to deprecate the `Mesh2` prefix and clean up our dimension, coordinate, and connectivity names to be more clear & pythonic.
> > When we make this change, this is how I see this being implemented
> > #### `Mesh2_face_edges`
> > ⟹
> > `face_edge_connectivity`
> > #### `face_edge_cart`
> > ⟹
> > `face_edges_xyz` (or similar)
> > For now, maybe a `Grid` helper function that is defined as follows would get the job done without needing to create any new public attributes.
> > ```
> > def get_face_edges(self, coord_type: Optional[str] = "latlon"):
> >     if coord_type == "latlon":
> >         # index lat/lon coords and return face edges
> >     elif: coord_type = "cartesian":
> >         # index x/y/z coords and return face edges
> > ```
> > 
> > 
> > Having similar functions for face nodes and all other connectivities would be really useful!
> 
> Thank you for you advice. However, I never plan to put this into our `Grid` attribute, this will just serve as a little helper function to conveniently preprocess the data for my following geometry functionalities. That's also why I didn't use `Grid.face_edge_carts` as my title but instead just `face_edg_carts`

sounds good! I'll move what I mentioned into a separate issue, since I think that would be useful for the user to have too.

**Comment by hongyuchen1030** [comment]
@aaronzedwick Can you help me implement this functionality? Thank you very much!

**Comment by philipc2** [comment]
> @aaronzedwick Can you help me implement this functionality? Thank you very much!

I still think we should hesitate to make a helper function for this until we figure out a good way to include it within our API, since this functionality does seem like it would be usefull for the user. For now, I would use this code within your implementation. 

```Python
face_edges = uxgrid.Mesh2_face_edges.values
x = uxgrid.Mesh2_node_cart_x.values # (n_node, )
y = uxgrid.Mesh2_node_cart_y.values # (n_node, )
y = uxgrid.Mesh2_node_cart_z.values # (n_node, )

def 
face_edge_x = x[face_edges] # (n_edge, 2)
face_edge_y = y[face_edges] # (n_edge, 2)
face_edge_z = z[face_edges] # (n_edge, 2)

face_edges_cart = np.vstack([face_edge_x, face_edge_y, face_edge_z]).T # (n_edge, 2, 3)
```

**Comment by hongyuchen1030** [comment]
> > @aaronzedwick Can you help me implement this functionality? Thank you very much!
> 
> I still think we should hesitate to make a helper function for this until we figure out a good way to include it within our API, since this functionality does seem like it would be usefull for the user. For now, I would use this code within your implementation.
> 
> ```python
> face_edges = uxgrid.Mesh2_face_edges.values
> x = uxgrid.Mesh2_node_cart_x.values # (n_node, )
> y = uxgrid.Mesh2_node_cart_y.values # (n_node, )
> y = uxgrid.Mesh2_node_cart_z.values # (n_node, )
> 
> def 
> face_edge_x = x[face_edges] # (n_edge, 2)
> face_edge_y = y[face_edges] # (n_edge, 2)
> face_edge_z = z[face_edges] # (n_edge, 2)
> 
> face_edges_cart = np.vstack([face_edge_x, face_edge_y, face_edge_z]).T # (n_edge, 2, 3)
> ```

Does this codes perform the edges for each face in a counterclockwise order? Also it doesn't meet my input requirement , I need the following data presentation

Face A: `[[v1.coord, v2.coord], [v2. coord, v3.coord], [v3.coord, v1.coord]]`

Certainly! Here is a suggested reply to the GitHub message:

---

Thank you for your insights and the code snippet provided. I do have a couple of questions and suggestions to make sure we're on the same page and moving forward effectively.

Firstly, I'm wondering about the order of the edges for each face; does the provided code ensure that the edges are arranged in a counterclockwise order? The reason I'm asking is that the orientation of the edges is crucial for some of the subsequent calculations in my implementation.

Secondly, I noticed that the data structure of the resulting `face_edges_cart` doesn't exactly match the format I require. For my purposes, it would be extremely helpful to have the data structured as follows for each face:

```python
Face A: `[[v1.coord, v2.coord], [v2.coord, v3.coord], [v3.coord, v1.coord]]`
```

I understand the concerns about integrating a helper function into our API without a clear path forward. However, I believe that having a small utility function to transform the data into the required format would be highly beneficial, not just for my current task but also for potential reuse in future tasks. It may not necessarily need to be a part of our public API, but having it available would streamline the process significantly.

I want to emphasize that this step is important for the latlon bound functionality. I'm keen to avoid any potential stalling in the progress of this feature. As what happened during our redesign was all my development was blocked.

I'm open to any suggestions on the API design and am more than willing to contribute to finding a solution that fits well within our existing structure. For now, could we consider implementing this helper function for internal use, ensuring that it's well-documented and tested so that it can be easily integrated or adapted for API inclusion in the future if we decide to go that route?

**Comment by philipc2** [comment]
> This feature aims to build a face_edge_cart representation: an ndarray that describes a face polygon through its edges in Cartesian coordinates. The representation is shaped as (n_edges, 2, 3)

After thinking about it, the explanation I gave was for `edge_faces_cart`, not `face_edges_cart`. Shouldn't the dimension of `face_edges_cart` be `(n_faces, n_max_edges_per_face, 2, 3)`? It would contain the Cartesian coordinates `(3)` for the nodes `(2)` that make up each edge in each face `(n_face, n_max_edges_per_face`).

This would change the code-snippet that I provided to the following

```Python
face_edges = uxgrid.Mesh2_face_edges.values # (n_face, n_max_edges_per_face)
n_max_edges = uxgrid.nNodes_per_face.values # (n_face, )
x = uxgrid.Mesh2_node_cart_x.values # (n_node, )
y = uxgrid.Mesh2_node_cart_y.values # (n_node, )
y = uxgrid.Mesh2_node_cart_z.values # (n_node, )

face_edge_x = []
face_edge_y = []
face_edge_z = []
for cur_face_edge, cur_max_edges in zip(face_edges, n_max_edges_per_face):
    # each list after iteration will be (n_face, n_max_edges_per_face, 2)
    face_edge_x.append(x[cur_face_edge[0:cur_max_edges])
    face_edge_y.append(y[cur_face_edge[0:cur_max_edges])
    face_edge_z.append(z[cur_face_edge[0:cur_max_edges])

# this should work, might need to slightly modify 
face_edges_cart = np.vstack([np.array(face_edge_x), np.array(face_edge_y), np.array(face_edge_z])).T # (n_face, n_max_edge_per_face, 2, 3)


```


> Firstly, I'm wondering about the order of the edges for each face; does the provided code ensure that the edges are arranged in a counterclockwise order? The reason I'm asking is that the orientation of the edges is crucial for some of the subsequent calculations in my implementation.

If the edges in `Grid.Mesh2_face_edges` have the correct orientation, then the resulting array above should too.

**Comment by aaronzedwick** [comment]
> @aaronzedwick Can you help me implement this functionality? Thank you very much!

Sure thing!

**Comment by aaronzedwick** [comment]
Is the goal of this to have face_edges_cart hold all the edges of a face in one attribute?

**Comment by aaronzedwick** [comment]
@philipc2 @hongyuchen1030 I will put a PR together for this, hopefully I can have it up for y’all to look at by the start of next week.

**Comment by philipc2** [comment]
> @philipc2 @hongyuchen1030 I will put a PR together for this, hopefully I can have it up for y’all to look at by the start of next week.

I would suggest starting with a `_build_xyz_face_edges()` and `_build_latlon_face_edges()`, which will eventually be used by `Grid.get_face_edges(self, coord_type: Optional[str] = "latlon")`. This would return the desired face edges, and could be what @hongyuchen1030  is looking for too.

**Comment by hongyuchen1030** [comment]
> @philipc2 @hongyuchen1030 I will put a PR together for this, hopefully I can have it up for y’all to look at by the start of next week.

Thank you very much for your help. I had already implemented this function last year and I could create a PR for my Draft today so that you can directly work on it! I will really appreciate your help for putting my draft into the production

**Comment by hongyuchen1030** [comment]
> @philipc2 @hongyuchen1030 I will put a PR together for this, hopefully I can have it up for y’all to look at by the start of next week.

Thank you very much for your help. I had already implemented this function last year and I could create a PR for my Draft today so that you can directly work on it! I will really appreciate your help for putting my draft into the production

> > Is the goal of this to have face_edges_cart hold all the edges of a face in one attribute?
> 
> I think for the purpose of @hongyuchen1030's work, we wouldn't need to necessarily store/cache it since it would be used as a variable throughout the function she is developing.
> 
> However, from a user-api standpoint, it might be worth storing it as an attribute, or at the least supporting a getting function
> 
> ```python
> Grid.get_face_edges(self, coord_type: Optional[str] = "latlon")
> ```
> 
> This is assuming `Mesh2_face_edges` gets renamed to `face_edge_connectivity` to avoid conflicts within the namespace.

We can just build this functionality as helper right now. And then in the future we can wrap it up for the user API. In this way our process can be proceed smoothly.

**Comment by philipc2** [comment]
> > @philipc2 @hongyuchen1030 I will put a PR together for this, hopefully I can have it up for y’all to look at by the start of next week.
> 
> Thank you very much for your help. I had already implemented this function last year and I could create a PR for my Draft today so that you can directly work on it! I will really appreciate your help for putting my draft into the production
> 
> > > Is the goal of this to have face_edges_cart hold all the edges of a face in one attribute?
> > 
> > 
> > I think for the purpose of @hongyuchen1030's work, we wouldn't need to necessarily store/cache it since it would be used as a variable throughout the function she is developing.
> > However, from a user-api standpoint, it might be worth storing it as an attribute, or at the least supporting a getting function
> > ```python
> > Grid.get_face_edges(self, coord_type: Optional[str] = "latlon")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is assuming `Mesh2_face_edges` gets renamed to `face_edge_connectivity` to avoid conflicts within the namespace.
> 
> We can just build this functionality as helper right now. And then in the future we can wrap it up for the user API. In this way our process can be proceed smoothly.

Sounds like a plan!
