### ISSUE TITLE
Rename the module `Grid.lines` to `Grid.arcs`

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#533]
**Describe the feature you'd like added to this project**
Our project aims to provide geometry operations on a unit sphere, and we operate under the assumption that all edges of a polygon are either great circle arcs or constant latitude arcs. Therefore, we are dealing with arcs instead of straight lines, making the name Grid.lines misleading and potentially confusing for users.

**Describe the solution you'd like**
Rename the module `Grid.lines` to `Grid.arcs`

**Comment by philipc2** [comment]
This is a good suggestion; it'll make our documentation more consistent.

**Comment by hongyuchen1030** [comment]
> This is a good suggestion; it'll make our documentation more consistent.
> 
> I can make a quick PR for this tomorrow if you'd like me to handle it!

Thank you very much for your help!
