### ISSUE TITLE
Calculate the weight for each face on the constant latitude

### ISSUE THREAD

**Issue by hongyuchen1030** [UXARRAY/uxarray#544]
**Describe the feature you'd like added to this project**
The function calculates the weights of grid faces at a specific constant latitude, facilitating accurate non-conservative zonal averages in climate and oceanographic data analysis. This addition aims to optimize and simplify user workflows within our library.

**Link to original functionality implementation elsewhere, if applicable**

**Links to other examples, if applicable**

**Describe the solution you'd like**

- Take a constant latitude as input and compute the perimeter of the corresponding circle.
- Identify the intervals of longitude that overlap with each face of the grid.
- Calculate the weight of each face based on these intervals and the total perimeter.
- Handle any errors or edge cases gracefully, ensuring that the function is robust and user-friendly.

**Additional context**

**Comment by erogluorhan** [comment]
@hongyuchen1030 can you please provide an actual description of this issue above? The original text doesn't seem to be adding anything to the issue template.

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030 can you please provide an actual description of this issue above? The original text doesn't seem to be adding anything to the issue template.

Yes, I will provide a more detailed description here and relate it to my draft PR.
