### ISSUE TITLE
Investigate `Dask` Compatibility 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#560]
### Proposed new feature or change:

Look into how `Dask` interacts with our core data structures (`UxDataArray`, `UxDataset`, `Grid`), especially sections that have `.values` and `.data` calls.

**Comment by erogluorhan** [comment]
This is much needed to be included in our performance & benchmarking efforts! Here is a [link](https://github.com/UXARRAY/uxarray/pull/439#discussion_r1376844770) to an elaboration on the concerns.

**Comment by philipc2** [comment]
@philipc2 

Convert this to a milestone?

**Comment by erogluorhan** [comment]
Sounds good to me

**Comment by philipc2** [comment]
Closing this in favor of linking specific issues to https://github.com/UXARRAY/uxarray/milestone/10
