### ISSUE TITLE
Add Cartesian Support for Nearest Neighbor Remapping

### ISSUE THREAD

**Issue by aaronzedwick** [UXARRAY/uxarray#566]
### Proposed new feature or change:

The current implementation of the nearest neighbor remapping only works for latlon. Now that the KDTree implementation is merged we can support a nearest neighbor remapping using cartesian coordinates as well.

**Comment by philipc2** [comment]
This would be a great addition. While working on the Nearest Neighbor grid subsetting (NOT remapping), I've been doing something like the following:

```Python
    def nearest_neighbors(self,
                          center_coord,
                          k,
                          query_type="nodes",
                          coord_type="spherical",
                          tree_type="BallTree"):
        _uxgrid = None
        return _uxgrid
```

We should be able to select these three options (query, coord, and tree types) to select what data structure to use for the nearest neighbor computation. I'd like to see if you had any ideas for parameter variable names,

**Comment by aaronzedwick** [comment]
Would `query_location` or `query_data_location` work better? Or maybe just `data_location`. I feel like `query_type` doesn't really describe what the parameter is selecting.

**Comment by philipc2** [comment]
> Would `query_location` or `query_data_location` work better? Or maybe just `data_location`. I feel like `query_type` doesn't really describe what the parameter is selecting.

How about the following parameters

`feature`: "nodes" or "face centers" (still think we need a better name for these too)
`coordinates`: "spherical" or "cartesiain"
`tree`: "BallTree` or "KDTree`

**Comment by aaronzedwick** [comment]
> > Would `query_location` or `query_data_location` work better? Or maybe just `data_location`. I feel like `query_type` doesn't really describe what the parameter is selecting.
> 
> How about the following parameters
> 
> `feature`: "nodes" or "face centers" (still think we need a better name for these too) `coordinates`: "spherical" or "cartesiain" `tree`: "BallTree` or "KDTree`

Coordinates and tree sound good, I still think feature doesn't really describe what it lets the user do. The point of the parameter is to let the user decided to make the tree either from nodes or face centers. Feature doesn't really seem to describe that in my opinion. What about `location`?

**Comment by philipc2** [comment]
> > > Would `query_location` or `query_data_location` work better? Or maybe just `data_location`. I feel like `query_type` doesn't really describe what the parameter is selecting.
> > 
> > 
> > How about the following parameters
> > `feature`: "nodes" or "face centers" (still think we need a better name for these too) `coordinates`: "spherical" or "cartesiain" `tree`: "BallTree` or "KDTree`
> 
> Coordinates and tree sound good, I still think feature doesn't really describe what it lets the user do. The point of the parameter is to let the user decided to make the tree either from nodes or face centers. Feature doesn't really seem to describe that in my opinion. What about `location`?

I think `location` is good!
