### ISSUE TITLE
Performance Comparison Between BallTree and KDTree

### ISSUE THREAD

**Issue by aaronzedwick** [UXARRAY/uxarray#572]
### Proposed new feature or change:

Do a performance comparison between the balltree and kdtree implementation in UXarray and compare the two using a large scale mesh. Doing this in a Juypter notebook would probably be ideal.

**Comment by aaronzedwick** [comment]
@philipc2 if you could get me that mesh you mentioned for this that would be great. Also, any advice on the best ways to make this comparison and different things I should test would be appreciated.

**Comment by philipc2** [comment]
> @philipc2 if you could get me that mesh you mentioned for this that would be great. Also, any advice on the best ways to make this comparison and different things I should test would be appreciated.

They're on the NCAR HPC right now, I'll get them downloaded and uploaded to google drive today.

**Comment by philipc2** [comment]
Initially, a simple notebook comparing:
1. Execution time of Construction of each Tree
2. Execution time of some number of queries for each tree

This doesn't have to be formal, but I'm extremely interested to see how it performs. We can convert some of this into a Remapping usage example eventually.

**Comment by aaronzedwick** [comment]
Awesome, thank you!

**Comment by aaronzedwick** [comment]
> > @philipc2 if you could get me that mesh you mentioned for this that would be great. Also, any advice on the best ways to make this comparison and different things I should test would be appreciated.
> 
> They're on the NCAR HPC right now, I'll get them downloaded and uploaded to google drive today.

Could you share the google drive link whenever it's up?

**Comment by philipc2** [comment]
> > > @philipc2 if you could get me that mesh you mentioned for this that would be great. Also, any advice on the best ways to make this comparison and different things I should test would be appreciated.
> > 
> > 
> > They're on the NCAR HPC right now, I'll get them downloaded and uploaded to google drive today.
> 
> Could you share the google drive link whenever it's up?

I'm waiting to hear back from @erogluorhan whether I can share this dataset with non-NCAR collaborators. In the meantime, I can get you two others s as a comparison, but they wont be as large

**Comment by rajeeja** [comment]
Use ASV benchmarks for showcasing this.

**Comment by aaronzedwick** [comment]
Completed by #870
