### ISSUE TITLE
Read from HTTPS Test Failing due to Broken URL

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#582]
### Version

v2023.11.1

### How did you install UXarray?

Source

### What happened?

https://github.com/UXARRAY/uxarray/blob/68fc9edd64272aca57853d23bedfebb0fe9e35c3/test/test_dataset.py#L70-L79

This test fails due to a broken link.

### What did you expect to happen?

Tests should pass as expected

**Comment by rljacob** [comment]
The filesystem holding that file was offline this morning for an fs check.  Its back now.
