### ISSUE TITLE
Install SpatialPandas from Source 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#588]
#574 changes the dependency of spatial pandas to build from source due to a recent push that was made that effects the performance of GeoDataFrame conversions.

Once this is released through Conda, switch back to installing via Conda.

**Comment by maximlt** [comment]
Hi @philipc2, [spatialpandas 0.4.10](https://github.com/holoviz/spatialpandas/releases/tag/v0.4.10) was released on PyPI and on conda-forge (the release on the *defaults* anaconda channel should follow shortly).

**Comment by philipc2** [comment]
> Hi @philipc2, [spatialpandas 0.4.10](https://github.com/holoviz/spatialpandas/releases/tag/v0.4.10) was released on PyPI and on conda-forge (the release on the _defaults_ anaconda channel should follow shortly).

Fantastic! Thanks for the heads up!
