### ISSUE TITLE
Compute and Populate Edge Centroid Coordinates 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#589]
### Proposed new feature or change:

Compute and Populate the following variables, which represent the coordinates of the centroid of each edge.
* `edge_lon`, `edge_lat`
* `edge_x`, `edge_y`, `edge_z` 

This will most likely employ the same Cartesian average scheme used for the face centroid computations.

**Comment by philipc2** [comment]
@aaronzedwick 

This should be very similar to what you've done for computing the `face_lon` and `face_lat` values.

**Comment by aaronzedwick** [comment]
Okay! Sounds great, I will get started on it!
