### ISSUE TITLE
Accessor API for Remapping

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#629]
### Proposed new feature or change:

Use an accessor-based implementation for remapping, similar to our `.plot` and `subset` functionality

Instead of:
```Python
uxds.nearest_neighbor_remap()
```

We should employ:
```Python
uxds.remap.nearest_neighbor()
```

**Comment by philipc2** [comment]
@aaronzedwick 

Let me know if you'd be interested in tackling this, I think it would be a nice opportunity to learn some neat things about python OOP.

The implementation would be almost exactly the same as https://github.com/UXARRAY/uxarray/pull/616

**Comment by aaronzedwick** [comment]
> @aaronzedwick
> 
> Let me know if you'd be interested in tackling this, I think it would be a nice opportunity to learn some neat things about python OOP.
> 
> The implementation would be almost exactly the same as #616 under the "subset" directory.

Sure, I would love to!

**Comment by philipc2** [comment]
> > @aaronzedwick
> > Let me know if you'd be interested in tackling this, I think it would be a nice opportunity to learn some neat things about python OOP.
> > The implementation would be almost exactly the same as #616 under the "subset" directory.
> 
> Sure, I would love to!

Great! Let me know if you have any questions :)
