### ISSUE TITLE
Conda home should have a description

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#63]
The "description" part of our [conda page ](https://anaconda.org/conda-forge/uxarray) is empty. It would be good to put an informative text there

<img width="513" alt="image" src="https://user-images.githubusercontent.com/32553057/177685069-f1eb4bd7-e5f6-42ea-9557-c7f78b68baca.png">

**Comment by erogluorhan** [comment]
@michaelavs @marodrig 

Could we please prioritize this?

**Comment by marodrig** [comment]
@erogluorhan I have access to all the geocat-* packages on anaconda.com, but I don't have access to uxarray to add or modify the description.

**Comment by erogluorhan** [comment]
> @erogluorhan I have access to all the geocat-* packages on anaconda.com, but I don't have access to uxarray to add or modify the description.

I think the "Edit" access is open for us for NCAR channel packages only; I thought for conda-forge packages, we might need to add a description using the feedstock repo?

**Comment by michaelavs** [comment]
@erogluorhan @marodrig 
It would be through the feedstock repo and looks like it is an update to the [meta.yaml](https://github.com/conda-forge/metpy-feedstock/blob/main/recipe/meta.yaml) file (based on metpy, which has a description on conda-forge page and then looking through their feedstock mata.yaml which is what is linked)

**Comment by marodrig** [comment]
@erogluorhan @michaelavs I created a [PR](https://github.com/conda-forge/uxarray-feedstock/pull/6) with the updated meta.yaml file.

**Comment by erogluorhan** [comment]
@marodrig It looks like the new build after the PR got merged has been generated, but I can't see the description field is populated yet. (cc @michaelavs )

**Comment by marodrig** [comment]
@erogluorhan Ryan May has helped me in updating the description for the conda page.

**Comment by erogluorhan** [comment]
> 

Sounds good! Was it like he had the "Edit" proveleges?

**Comment by marodrig** [comment]
Yes. There is no automatic synchronization of the recipe (meta.yaml) after the initial recipe creation, Ryan had to manually edit the description to match the updated recipe.
