### ISSUE TITLE
 grid.query_radius ValueError if return_distance=False

### ISSUE THREAD

**Issue by ahijevyc** [UXARRAY/uxarray#633]
### Version

2023.12.0

### How did you install UXarray?

Conda

### What happened?

ValueError when grid.query_radius return_distance=False
If return_distance=False, query_radius returns one value (ind), not two (ind, d).

> File /glade/work/ahijevyc/conda-envs/mpas/lib/python3.11/site-packages/uxarray/grid/neighbors.py:429, in BallTree.query_radius(self, xy, r, xy_in_radians, return_distance, count_only, sort_results)
>     425     return count
>     427 else:
> --> 429     ind, d = self._current_tree().query_radius(xy, r, return_distance,
>     430                                                count_only, sort_results)
>     432     ind = np.asarray(ind[0], dtype=INT_DTYPE)
>     434     if xy.shape[0] == 1:
> 
> ValueError: too many values to unpack (expected 2)

### What did you expect to happen?

return ind without distance

### Can you provide a MCVE to repoduce the bug?

```python
tried to write a small uxarray dataset but couldn't do it easily
```

**Comment by aaronzedwick** [comment]
Good catch @ahijevyc! I have fixed this and will add it to the tree refactor! Thanks!
