### ISSUE TITLE
Implement open_file method of Grid class, support  non xarray formats Shapefile/Geojson 

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#635]
### Proposed new feature or change:

Add reader shapefile/geojson file
There is post about some existing options [here](https://gis.stackexchange.com/questions/113799/reading-shapefile-in-python)

UXarray requires only certain aspects from the file - coords, connectivity, so implementing something from scratch would be the way to do. Details about the format is [here](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf)

**Comment by kmsampson** [comment]
Shapefile is a good place to start, but an old format with limitation of 2GB. I suggest adopting support for GeoPandas, which contains drivers for many geospatial formats beyond shapefile, including GeoPackage, GeoDatabase, GeoJSON, shapefile, and others.

**Comment by rajeeja** [comment]
> Shapefile is a good place to start, but an old format with limitation of 2GB. I suggest adopting support for GeoPandas, which contains drivers for many geospatial formats beyond shapefile, including GeoPackage, GeoDatabase, GeoJSON, shapefile, and others.

added base test and reader for shapefile and geojson file. please review.
