### ISSUE TITLE
Numba Wheel Building Process Makes CI Ustream Fail

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#653]
See a failing [CI Upstream action](https://github.com/UXARRAY/uxarray/actions/runs/7468831899/job/20327839144) for reference. For now, we've removed Numba from upstream testing, but for future we need to figure this.

**Comment by philipc2** [comment]
@erogluorhan 

This should be resolved after these commits, correct?

![image](https://github.com/UXARRAY/uxarray/assets/67855069/5f14c272-502d-44cc-a792-e6e3efa82864)

**Comment by erogluorhan** [comment]
> @erogluorhan
> 
> This should be resolved after these commits, correct?
> 
> ![image](https://private-user-images.githubusercontent.com/67855069/296381903-5f14c272-502d-44cc-a792-e6e3efa82864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDQxMTcsIm5iZiI6MTcwNTEwMzgxNywicGF0aCI6Ii82Nzg1NTA2OS8yOTYzODE5MDMtNWYxNGMyNzItNTAyZC00NGNjLWE3OTItZTZlM2VmYTgyODY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDIzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOWQzMjA1MGQ1YTg0NWZiYzdlNDU4ZjlhOGNjMmRjZmM0Y2M1MTE1ZTM0ZTQwNmIxYzZhYjI0MTJiN2UxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RjaN6o-M8aLgdpyLvOauKpAliooOdrVL1wmjRgePQmQ)

No, these commits just removed Numba from the upstream testing process for now until we figure out having Numba without failures

**Comment by philipc2** [comment]
> > @erogluorhan
> > 
> > This should be resolved after these commits, correct?
> > 
> > ![image](https://private-user-images.githubusercontent.com/67855069/296381903-5f14c272-502d-44cc-a792-e6e3efa82864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDQxMTcsIm5iZiI6MTcwNTEwMzgxNywicGF0aCI6Ii82Nzg1NTA2OS8yOTYzODE5MDMtNWYxNGMyNzItNTAyZC00NGNjLWE3OTItZTZlM2VmYTgyODY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDIzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOWQzMjA1MGQ1YTg0NWZiYzdlNDU4ZjlhOGNjMmRjZmM0Y2M1MTE1ZTM0ZTQwNmIxYzZhYjI0MTJiN2UxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RjaN6o-M8aLgdpyLvOauKpAliooOdrVL1wmjRgePQmQ)
> 
> No, these commits just removed Numba from the upstream testing process for now until we figure out having Numba without failures. Thus, let us keep this issue open until then. 
> 
> FYI: The `numba_upstream` branch is for adding numba nack into upstream testing, but if you give it a try with the CI Upstream, you will see it failing.

Got it!
