### ISSUE TITLE
User API - Methods from Accessors are not clickable

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#654]
The methods  in the user API that belong to an accessor class cannot be clicked and expanded. They should be expandable just like the others.

See an example below:

<img width="810" alt="image" src="https://github.com/UXARRAY/uxarray/assets/32553057/c84a4e30-ef37-4c8a-a24b-3aa04a4aca7e">

**Comment by philipc2** [comment]
@dcherian 

Do you have any points on how this is handled with `xarray`?

**Comment by dcherian** [comment]
https://github.com/xarray-contrib/sphinx-autosummary-accessors

**Comment by philipc2** [comment]
> https://github.com/xarray-contrib/sphinx-autosummary-accessors

Thank you!
