### ISSUE TITLE
uxtree.query_radius returns only one list even though multiple points provided

### ISSUE THREAD

**Issue by ahijevyc** [UXARRAY/uxarray#663]
### Version

2023.12.0 main branch pulled Jan 14, 2024

### How did you install UXarray?

Source

### What happened?

Asked for neighbors within r degrees of n locations on a uxarray grid. uxtree.query_radius only returned one list. I think it corresponded to the first location. 

### What did you expect to happen?

It should return a list of n lists, one for each location.  Don't return just a list of neighbors for the first location.

### Can you provide a MCVE to repoduce the bug?

```python
import uxarray

grid_path = "/glade/campaign/mmm/parc/schwartz/MPAS/15-3km_mesh/mpas_init/static.nc"
data_path = "/glade/campaign/mmm/parc/schwartz/HWT2023/mpas/2023053100/post/mem_4/diag.2023-06-01_12.00.00.nc"

uxds = uxarray.open_dataset(grid_path, data_path, use_dual=False)
uxtree = uxds.uxgrid.get_ball_tree(coordinates="face centers")
c = [
    [-100, 40],
    [-101, 38],
    [-102, 38],
]
idxs = uxtree.query_radius(c, 0.05)
print(idxs)
```

`[6487403 6487413 6487423 6487405 6487421  120343  120348  120339  120342
  120344  120345 6487422  120338]`
```

**Comment by philipc2** [comment]
Thanks for catching this, we'll get this patched & add a test case to cover this.
