### ISSUE TITLE
User-Selectable Tree Remapping

### ISSUE THREAD

**Issue by aaronzedwick** [UXARRAY/uxarray#668]
### Proposed new feature or change:

Currently, our remapping uses default trees, `ball_tree` for spherical and `kd_tree` for cartesian remapping. We should let the user decide if they want to change between the two.

**Comment by philipc2** [comment]
@aaronzedwick

**Comment by aaronzedwick** [comment]
Closing as it is not advantageous to let the user choose the tree structure. It can cause incorrect remapping results if the wrong combinations of trees and coordinates are picked.
