### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#69]
_Also mentioned in https://github.com/UXARRAY/uxarray/discussions/88#discussioncomment-3335720_

Before our next release, it would be beneficial to have 1-2 usage examples of uxarray for real-world use cases, similar to what [Xarray](https://docs.xarray.dev/en/stable/gallery.html) has.

**Ideas:**
* Visualizing Unstructured Grids with Delaunay Triangulation 
* [Example with Integrate if PR gets approved] 

Any other suggestions?

**Comment by rljacob** [comment]
Open in one format and write in another?
