### ISSUE TITLE
First run of ASV Benchmarking CI failed

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#699]
### Version

main branch

### How did you install UXarray?

Source

### What happened?

See the [failure](https://github.com/UXARRAY/uxarray/actions/runs/7881684733/job/21505703959) that was ran right after the PR #694 was merged.

### What did you expect to happen?

CI to succeed; however, just an fyi: geocat-comp's ASV CI also [started to fail](https://github.com/NCAR/geocat-comp/actions/runs/7881645531/job/21505603710) tonight due to the same reason

**Comment by HaoZeke** [comment]
This is because of a change in the default build command in asv. As a workaround, build can be added to the requirements or the build command can be set manually to the older python setup.py build invocation.
