### ISSUE TITLE
Codecov upload failures

### ISSUE THREAD

**Issue by anissa111** [UXARRAY/uxarray#703]
Codecov uploads have been silently failing for around 25 days, see [the last reported commits](https://app.codecov.io/gh/UXARRAY/uxarray/commits) and [your logs here](https://github.com/UXARRAY/uxarray/actions/runs/8057964419/job/22010007742#step:10:21)

We fixed the same issue in geocat-comp (https://github.com/NCAR/geocat-comp/pull/566) by following this documentation: https://docs.codecov.com/docs/adding-the-codecov-token

**Comment by rajeeja** [comment]
It seems [token](https://github.com/UXARRAY/uxarray/actions/runs/9088429827/job/24977961892#step:10:37) is missing.
Do you have the codecov account for our project? we might just need to supply the token from there to the CI call.

**Comment by erogluorhan** [comment]
See PR #791 . I've had a personal codecov account. For UXarray, I've used that one, added uxarray, and used its token. Codecov states that it is totally free for any open-source project, so I feel my personal (not business) account should be good here, any thoughts? cc @anissa111 @philipc2
