### ISSUE TITLE
Ability to Represent Structured Grids

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#725]
### Proposed new feature or change:

Introduce the ability to load in a regular structured grid and represented it as unstructured.

**Comment by erogluorhan** [comment]
Just to clarify, this is not remapping, this is aimed at reading in structured grids as they are a special case of unstructured grids. 

UXarray currently requires coordinates to be one-dimensional and connectivities to be explicitly defined. We'd need to convert 2D coords and underlying connectivity between lat/lon cells of structured grids into 1D coords and explicitly defined connectivities, respectively, to achieve this.
