### ISSUE TITLE
Various typo issues in documentation

### ISSUE THREAD

**Issue by dfg-13** [UXARRAY/uxarray#735]
### Version

v2024.02.0

### How did you install UXarray?

Source

### What happened?

[Subsetting an Unstructured Grid: Analysis Over Chicago](https://uxarray.readthedocs.io/en/latest/examples/009-subsetting.html#bounding-box) has a typo in the markdown where the graphic for a note does not display. Due to the typo, the text is displayed as such:
> :::{note} Specifying which element to query (i.e. nodes, edgecenters, or face centers) is supported by all subsetting methods. :::

Another typo exists under the section [configure uxarray conda environment}(https://uxarray.readthedocs.io/en/latest/contributing.html#configure-uxarray-conda-environment). Small issue with the capitalization of the "h" in the word "The" from the text:

> THe above commands will use the environment.yml conda environment definition file that is hosted under the ci folder and create a conda environment with the name uxarray_build. Once you activate that environment with the help of the second command, you will be able to develop UXarray codes in your local configuration.

These are the typos I've found so far, and I'll be putting together a PR to fix them.

### What did you expect to happen?

In regards to the issue found under [Subsetting an Unstructured Grid: Analysis Over Chicago](https://uxarray.readthedocs.io/en/latest/examples/009-subsetting.html#bounding-box), it should look like a blue note box much like the screenshot shown below. The following is a screenshot taken from [Visualizing Data as Points](https://uxarray.readthedocs.io/en/latest/examples/008-point-viz.html):
![image](https://github.com/UXARRAY/uxarray/assets/54779078/8ea13d3f-f5cc-405f-8927-7e25a17b7852)

As for the typo found under [configure uxarray conda environment}(https://uxarray.readthedocs.io/en/latest/contributing.html#configure-uxarray-conda-environment), the "THe" should be "The".

### Can you provide a MCVE to repoduce the bug?

```python
Not applicable
```

**Comment by philipc2** [comment]
Hi @dfg-13 

Thank you for catching these and for putting a PR together!
