### ISSUE TITLE
Usage example on translating structured Xarray workflows to UXarray

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#742]
### Proposed new feature or change:

For the case where both a structured and unstructured grid representation of a dataset is available, showcase how how to translate the following workflows from standard Xarray on structured grids to UXarray
* Visualization 
* Analysis
* Data I/O

**Comment by erogluorhan** [comment]
Implemented [here](https://projectpythia.org/unstructured-grid-viz-cookbook/notebooks/03-uxarray-vis/002-xarray-to-uxarray.html) as part of our UXarray's Pythia cookbook.
