### ISSUE TITLE
Hard coded `decode_times` parameter in `ux.open_dataset`

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#766]
### Discussed in https://github.com/UXARRAY/uxarray/discussions/764

<div type='discussions-op-text'>

<sup>Originally posted by **tomvothecoder** April 15, 2024</sup>
Hi, I'm just wondering why `decode_times=False` is hard-coded in `ux.open_dataset()` and `ux.open_mfdataset()`? 

https://github.com/UXARRAY/uxarray/blob/54da444302425be04d33abe914062d8ffc5fed35/uxarray/core/api.py#L170-L171
https://github.com/UXARRAY/uxarray/blob/54da444302425be04d33abe914062d8ffc5fed35/uxarray/core/api.py#L259-L260

I'm trying to use xCDAT's temporal [APIs](https://xcdat.readthedocs.io/en/latest/generated/xcdat.temporal.TemporalAccessor.html) on `uxarray.UxDataset` objects, but those APIs require time coordinates to be decoded as `datetime` or `cftime` objects (`decode_times=True`).

### Workaround
I was able to decode time coordinates using [`xarray.decode_cf()`](https://docs.xarray.dev/en/stable/generated/xarray.decode_cf.html) with `decode_times=True` and `use_cftime=True`. All downstream xCDAT temporal APIs worked.  

**However, the issue is that `xarray.decode_cf()` returns an `xarray.Dataset` object, rather than the `uxarray.UxDataset` object. This means all of the `uxarray` attributes and operators are no longer accessible on the returned object.**
</div>

**Comment by tomvothecoder** [comment]
Do you think this will be able to make it in the upcoming release, which I assume is the beginning of May?

I'm doing a demo of UXarray with xCDAT on May 7th so it'd be great to have this change.

**Comment by philipc2** [comment]
> Do you think this will be able to make it in the upcoming release, which I assume is the beginning of May?
> 
> I'm doing a demo of UXarray with xCDAT on May 7th so it'd be great to have this change.

Yes! I'll be getting a fix in today, and it will be out in our April release.

**Comment by tomvothecoder** [comment]
Awesome. Thanks @philipc2!

**Comment by tomvothecoder** [comment]
> Yes! I'll be getting a fix in today, and it will be out in our April release.

Hi @philipc2, do UXarray releases typically happen at the end of the release month (e.g., end of April for `v2024.04.01`)? 

The attendees at the upcoming E3SM Tutorial Workshop will be using the [E3SM Unified Environment](https://github.com/E3SM-Project/e3sm-unified), which will include UXarray. I believe the latest version is going to be released on 4/29/24 (cc. @xylar). Just seeing if this fix will be available in a new version in time.

**Comment by philipc2** [comment]
> > Yes! I'll be getting a fix in today, and it will be out in our April release.
> 
> Hi @philipc2, do UXarray releases typically happen at the end of the release month (e.g., end of April for `v2024.04.01`)?
> 
> The attendees at the upcoming E3SM Tutorial Workshop will be using the [E3SM Unified Environment](https://github.com/E3SM-Project/e3sm-unified), which will include UXarray. I believe the latest version is going to be released on 4/29/24 (cc. @xylar). Just seeing if this fix will be available in a new version in time.

We typically do releases on the Tuesday of the final week of iteration. This would of been last week, but we had multiple presentations (EGU & NCAR ISS).

I'll be getting a release out today. 

![image](https://github.com/UXARRAY/uxarray/assets/67855069/6d257e6d-efc7-4bc5-af01-7a978e49aa25)

**Comment by tomvothecoder** [comment]
@philipc2 Awesome! Thank you for all your work and helping me out!

**Comment by chengzhuzhang** [comment]
@philipc2 Congratulation on the new release! Really appreciate your help to work with the E3SM Tutorial time line..

**Comment by philipc2** [comment]
> @philipc2 Congratulation on the new release! Really appreciate your help to work with the E3SM Tutorial time line..

Thank you! Don't hessite to reach out if anyone else comes up!
