### ISSUE TITLE
Adjust Colormap Anchors for UxDataArray Plotting

### ISSUE THREAD

**Issue by kylemnardi** [UXARRAY/uxarray#781]
I'm new to uxarray and attempting to visualize some climate model data on its native grid. I'm using `UxDataArray.plot()` and would like to adjust the colormap ranges. Is there an equivalent to vmin/vmax in the plotting function? I couldn't find any details in the documentation. Thanks!

**Comment by philipc2** [comment]
Hi @kylemnardi 

You can specify a `clim`, which takes in a tuple of the minimum and maximum value for the color bar range.

Some documentation on it can be found in the [Holoviews FAQ](https://holoviews.org/FAQ.html#:~:text=As%20in%20the,ylim%20plot%20options%3A)

[Here's an example in one of our Usage Examples](https://uxarray.readthedocs.io/en/latest/examples/009-subsetting.html#:~:text=clim%20%3D%20(uxds%5B%22relhum_200hPa%22%5D%5B0%5D.values.min()%2C%20uxds%5B%22relhum_200hPa%22%5D%5B0%5D.values.max()))

Additionally, here's a link to our [Visualization Cookbook](https://projectpythia.org/unstructured-grid-viz-cookbook/README.html) if you haven't seen it yet.

Hope this helps!

**Comment by kylemnardi** [comment]
Thanks @philipc2! This is exactly what I needed!

**Comment by zarzycki** [comment]
@philipc2 thanks for this! I now realize that I have access to the hv parameters which I found here: https://holoviews.org/reference_manual/holoviews.plotting.mpl.html ... e.g., labeling the colorbar, tweaking other things, etc. uxarray.plot seems to inherit all of this which is cool.

I think this would be a great notation somewhere in the uxarray cookbooks. I'm so used to vmin and vmax from mpl that it took me a sec to figure out what was up. I'm the kind of person who you need to hit over the head with a shovel to get up to speed, and I'm sure there are dozens of us! :)

**Comment by philipc2** [comment]
> @philipc2 thanks for this! I now realize that I have access to the hv parameters which I found here: https://holoviews.org/reference_manual/holoviews.plotting.mpl.html ... e.g., labeling the colorbar, tweaking other things, etc. uxarray.plot seems to inherit all of this which is cool.
> 
> I think this would be a great notation somewhere in the uxarray cookbooks. I'm so used to vmin and vmax from mpl that it took me a sec to figure out what was up. I'm the kind of person who you need to hit over the head with a shovel to get up to speed, and I'm sure there are dozens of us! :)

Thanks for the suggestion! We are planning to add a "Customization" section in the Cookbook that'll cover this and other customization options.
