### ISSUE TITLE
ASV Benchmark PR Workflow 

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#795]
It would be really useful to have a workflow that runs a series of core benchmarks (or all current benchmarks) on a pull request before merging it, providing a summary of the results.

This would help ensure that issues like #793 could be caught before merging. 

This workflow could be triggered by a maintainer (not run on every commit)

**Comment by kafitzgerald** [comment]
This is on the (mental) to do list for geocat-comp as well.  Excited to learn from you all if you get to it first!

FWIW [xarray has it set up](https://github.com/pydata/xarray/blob/main/.github/workflows/benchmarks.yml
) and there's a [nice overview on how to do this here](https://labs.quansight.org/blog/2021/08/github-actions-benchmarks).  Sorry if I already shared this - can't recall.

**Comment by philipc2** [comment]
> This is on the (mental) to do list for geocat-comp as well. Excited to learn from you all if you get to it first!
> 
> FWIW [xarray has it set up](https://github.com/pydata/xarray/blob/main/.github/workflows/benchmarks.yml) and there's a [nice overview on how to do this here](https://labs.quansight.org/blog/2021/08/github-actions-benchmarks). Sorry if I already shared this - can't recall.

Thanks for these! Something along the lines of the Xarray one would be exactly what I was envisioning.
