### ISSUE TITLE
E3SM Visualization Example

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#822]
A notebook showcasing basic plots of E3SM model output to put in our visualization gallery.

**Comment by rljacob** [comment]
What are you planning here?

**Comment by philipc2** [comment]
> What are you planning here?

@rytam2 has run the E3SM model for her past work and has some data she'd like to visualize. It would be a one-shot example notebook, something like this one that is in the works

file:///C:/tmp/mydocs/examples/visualization/3_75km_mpas.html
