### ISSUE TITLE
E3SM results visualization

### ISSUE THREAD

**Issue by evasinha** [UXARRAY/uxarray#843]
### Proposed new feature or change:

I would like to plot E3SM, `eam.h0` output files that are at `ne30np4.pg2`. As a first step, I am trying to read the grid file: 
```
import uxarray as ux

grid_path = file_path + 'ne30pg2_scrip_c20191218.nc'

uxgrid = ux.open_grid(grid_path)
print(uxgrid)
print(uxgrid.node_lon)
```

However as shown in the outputs below the lon values being read are  all zero:
```
<uxarray.Grid>
Original Grid Type: Scrip
Grid Dimensions:
  * n_node: 21727
  * n_face: 21600
  * n_max_face_nodes: 4
  * n_nodes_per_face: (21600,)
Grid Coordinates (Spherical):
  * node_lon: (21727,)
  * node_lat: (21727,)
  * face_lon: (21600,)
  * face_lat: (21600,)
Grid Coordinates (Cartesian):
Grid Connectivity Variables:
  * face_node_connectivity: (21600, 4)
Grid Descriptor Variables:

<xarray.DataArray 'node_lon' (n_node: 21727)>
array([0., 0., 0., ..., 0., 0., 0.])
Dimensions without coordinates: n_node
```

Can you provide a simple example of plotting E3SM unstructured outputs?

**Comment by rljacob** [comment]
The file can be found here:  https://web.lcrc.anl.gov/public/e3sm/inputdata/share/meshes/homme/ne30np8_scrip_c20191218.nc

**Comment by philipc2** [comment]
Hi @evasinha 

The minimal example you provided looks correct to me. The reason the `node_lon` appears to be all zeros is because it is only printing a handfull of the values for the repr.

<img width="415" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/11413fdb-10bd-4de0-bbc7-105464964cbf">

I'd suggest taking a look at our [User Guide section on Plotting ](https://uxarray.readthedocs.io/en/latest/user-guide/plotting.html)

@rytam2 is also working on an E3SM visualuzation notebook in #836

**Comment by evasinha** [comment]
Thanks @philipc2 

When I try to generate a plot using uxarray it show up as blank: 
```
import uxarray as ux
import matplotlib.pyplot as plt

grid_path = file_path + 'ne30pg2_scrip_c20191218.nc'
fname = '20240703_SSP245_ZATM_BGC_ne30pg2_f09_oEC60to30v3.eam.h0.2075-06.nc'

uxds = ux.open_dataset(grid_path, fname)

uxds['SFCO2'][0].plot()
plt.savefig('SFCO2.png')
```

Is it possible that there are some issues rendering the image and if so how can those be resolved?

**Comment by evasinha** [comment]
The file mentioned above can be downloaded from - https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.eva.sinha/tmp/

**Comment by philipc2** [comment]
@evasinha 

Here's a slightly modified example that works for me. Our plotting API is written using HoloViews, so I needed to make a few modifications to the code you provided.

```Python
import uxarray as ux
import holoviews as hv
hv.extension('matplotlib')

grid_path = "/Users/philipc/Downloads/ne30pg2_scrip_c20191218.nc"
data_path = "/Users/philipc/Downloads/20240703_SSP245_ZATM_BGC_ne30pg2_f09_oEC60to30v3.eam.h0.2075-06.nc"

uxds = ux.open_dataset(grid_path, data_path)

# generate and store a plot as a variable
out = uxds['SFCO2'][0].plot(backend='matplotlib', 
                            fig_size=350,
                            pixel_ratio=4.0)

# safe plot as a PNG
hv.save(out, 'SFCO2.png', fmt='png')
```

<img width="834" alt="image" src="https://github.com/UXARRAY/uxarray/assets/67855069/cb7ed878-514d-4d57-b912-818033ca0be0">

**Comment by evasinha** [comment]
@philipc2 Thank you very much for the modified working example. The modified script worked effortlessly for me as well.

**Comment by whannah1** [comment]
@philipc2 can you also provide an example that specifies the map projection?
