### ISSUE TITLE
installation page

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#884]
### Version

latest

### How did you install UXarray?

Pip

### What happened?

https://uxarray.readthedocs.io/en/latest/installation.html

referenced here: Documentation section has a installation hyperlink https://pypi.org/project/uxarray/ 

### What did you expect to happen?

404 Not Found

**Comment by aaronzedwick** [comment]
We have an installation page, it's just a different link: https://uxarray.readthedocs.io/en/latest/getting-started/installation.html

**Comment by rajeeja** [comment]
This seems to be fixed. Closing.
