### ISSUE TITLE
Retrieving values in _slice_from_grid needs to be avoided.

### ISSUE THREAD

**Issue by kjnam** [UXARRAY/uxarray#889]
### Version

v2024.07.1

### How did you install UXarray?

Conda

### What happened?

`_slice_from_grid` method in `UxDataArray` retrieves values and creates numpy array data after `isel`. See the lines 1080, 1085, and 1090 below:
https://github.com/UXARRAY/uxarray/blob/5410c4f0ebf699c72869dca2095cfc8ab7f61ec6/uxarray/core/dataarray.py#L1071-L1104

This collects values and creates ndarrays unnecessarily and prevents the function from staying in efficient distributed xarray/dask data structures when data are processed by chunks and multiple threads. It degrades performance significantly and require huge amount of memory.
The issue is avoided by not collecting values.

### What did you expect to happen?

The function keeps the data in xarray/dask during slicing, not collecting data into numpy arrays so that it takes advantage of xarray/dask.

**Comment by rajeeja** [comment]
it'd be good to see if changes here break or improve the performance of #836

**Comment by kjnam** [comment]
@rajeeja If #836 involves subsetting of a large grid, the change should improve the performance noticeably.
