### ISSUE TITLE
Add Cross sections

### ISSUE THREAD

**Issue by erogluorhan** [UXARRAY/uxarray#94]
Cross sections

_Originally posted by @erogluorhan in https://github.com/UXARRAY/uxarray/discussions/46#discussioncomment-2746616_

**Comment by brianpm** [comment]
Might want to compare with what MetPy does:
https://unidata.github.io/MetPy/latest/api/generated/metpy.interpolate.cross_section.html

**Comment by philipc2** [comment]
Closing this issue in favor of using a milestone for each type of cross-section we plan to introduce. 

https://github.com/UXARRAY/uxarray/milestone/31
