### ISSUE TITLE
to_linecollection issues with projection and global grid wrapping w/ mpl and cartopy

### ISSUE THREAD

**Issue by zarzycki** [UXARRAY/uxarray#984]
### Version

v2023.08.4

### How did you install UXarray?

Conda

### What happened?

I am probably doing something unintelligent, but say I want to print the polylines assocated with a uxarray grid. In theory, this should work with mpl + cartopy...

```
import uxarray as ux
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

base_path = "./"
grid_path = base_path + "outCSne30.ug"
data_path = base_path + "outCSne30_vortex.nc"
uxds = ux.open_dataset(grid_path, data_path)

projection = ccrs.PlateCarree()  # also tried ccrs.Orthographic(central_longitude=0, central_latitude=90)
lc = uxds.uxgrid.to_linecollection(projection=projection,override=True)

#segments = lc.get_segments()
#print(segments)

fig, ax = plt.subplots(1, 1, figsize=(10, 10), constrained_layout=True,
                       subplot_kw={'projection': ccrs.Orthographic(central_longitude=0, central_latitude=90)})

ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.COASTLINE)
ax.add_collection(lc)
ax.set_global()
plt.title("Grid Orthographic Projection")
plt.show()
```

It gives me the projection but a blank graph:

<img width="1036" alt="Screenshot 2024-10-01 at 9 28 36 AM" src="https://github.com/user-attachments/assets/bc79da78-8d82-4793-9474-d339b9767e97">

I can sneak around this by creating the LineCollection with uxarray and then unpacking it and redefining it with a PC projection. The below now gives me grid lines, but it doesn't appear to wrap accurately along the date line (-180/180).

```
import uxarray as ux
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.collections import LineCollection

base_path = "./"
grid_path = base_path + "outCSne30.ug"
data_path = base_path + "outCSne30_vortex.nc"
uxds = ux.open_dataset(grid_path, data_path)

lc_original = uxds.uxgrid.to_linecollection()
segments = lc_original.get_segments()
projection = ccrs.PlateCarree()
lc = LineCollection(segments, linewidths=0.5, colors='black', transform=projection)

fig, ax = plt.subplots(1, 1, figsize=(10, 10), constrained_layout=True,
                       subplot_kw={'projection': ccrs.Orthographic(central_longitude=0, central_latitude=90)})

ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.COASTLINE)
ax.add_collection(lc)
ax.set_global()
plt.title("Grid Orthographic Projection")
plt.show()
```

<img width="1033" alt="Screenshot 2024-10-01 at 9 33 37 AM" src="https://github.com/user-attachments/assets/9f3d242e-f9f4-459c-aad3-61b772915244">

So TL;DR two problems.
1. Trouble getting to_linecollection() to be transformed correctly
2. Lines not correctly wrapping around edges of mesh

If it's just something silly on my end (50/50 chance!), maybe we could add some additional lines to the mpl.ipynb notebook to help.

This may be tied to the periodic_elements option in to_polycollection() although the artifacts here aren't as pervasive.

### What did you expect to happen?

Expected to use to_linecollection() to create a grid skeleton I could then draw with different projections using mpl + cartopy.

### Can you provide a MCVE to repoduce the bug?

```python
import uxarray as ux
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib.collections import LineCollection

base_path = "./"
grid_path = base_path + "outCSne30.ug"
data_path = base_path + "outCSne30_vortex.nc"
uxds = ux.open_dataset(grid_path, data_path)

lc_original = uxds.uxgrid.to_linecollection()
segments = lc_original.get_segments()
projection = ccrs.PlateCarree()
lc = LineCollection(segments, linewidths=0.5, colors='black', transform=projection)

fig, ax = plt.subplots(1, 1, figsize=(10, 10), constrained_layout=True,
                       subplot_kw={'projection': ccrs.Orthographic(central_longitude=0, central_latitude=90)})

ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.COASTLINE)
ax.add_collection(lc)
ax.set_global()
plt.title("Grid Orthographic Projection")
plt.show()
```

**Comment by zarzycki** [comment]
Thanks @philipc2!

The user API doesn't mention periodic_elements: https://uxarray.readthedocs.io/en/v2024.02.0/user_api/generated/uxarray.Grid.to_linecollection.html

Although I thought I tried it and got an error. Maybe I messed something up...

FWIW, while that plot looks better, there does appear to be a weird collection of line segments right at the pole. Any idea if that's the mesh or the plotting? I can look later when I have some free time, too.

**Comment by philipc2** [comment]
> https://uxarray.readthedocs.io/en/v2024.02.0/user_api/generated/uxarray.Grid.to_linecollection.html

That appears to be an older release. here's our latest documentation:

https://uxarray.readthedocs.io/en/v2024.08.2/user_api/generated/uxarray.Grid.to_linecollection.html

> FWIW, while that plot looks better, there does appear to be a weird collection of line segments right at the pole. Any idea if that's the mesh or the plotting? I can look later when I have some free time, too.

That's most likely a slight artifact of the split polygons. I can look into it further.

**Comment by zarzycki** [comment]
Gah, I blame Google but I should have checked that.
